// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tramoseats_results.proto

package demetra.tramoseats.io.protobuf;

public final class TramoSeatsResultsProtos {
  private TramoSeatsResultsProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030tramoseats_results.proto\022\ntramoseats\032\r" +
      "toolkit.proto\032\016regarima.proto\032\010sa.protoB" +
      "9\n\036demetra.tramoseats.io.protobufB\027Tramo" +
      "SeatsResultsProtosP\000P\001P\002b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          demetra.toolkit.io.protobuf.ToolkitProtos.getDescriptor(),
          demetra.regarima.io.protobuf.RegArimaProtos.getDescriptor(),
          demetra.sa.io.protobuf.SaProtos.getDescriptor(),
        });
    demetra.toolkit.io.protobuf.ToolkitProtos.getDescriptor();
    demetra.regarima.io.protobuf.RegArimaProtos.getDescriptor();
    demetra.sa.io.protobuf.SaProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
