/*
* Copyright 2013 National Bank of Belgium
*
* Licensed under the EUPL, Version 1.1 or – as soon they will be approved 
* by the European Commission - subsequent versions of the EUPL (the "Licence");
* You may not use this work except in compliance with the Licence.
* You may obtain a copy of the Licence at:
*
* http://ec.europa.eu/idabc/eupl
*
* Unless required by applicable law or agreed to in writing, software 
* distributed under the Licence is distributed on an "AS IS" basis,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the Licence for the specific language governing permissions and 
* limitations under the Licence.
*/


package ec.tss.sa;

import ec.satoolkit.ISaSpecification;
import ec.tss.sa.documents.SaDocument;
import ec.tstoolkit.algorithm.IOutputFactory;
import nbbrd.service.Quantifier;
import nbbrd.service.ServiceDefinition;

/**
 * Output generated by ISaOutputFactory should use ec.tstoolkit.utilities.Id 
 * objects as context in their start/end methods
 * @author Jean Palate
 */
@ServiceDefinition(quantifier = Quantifier.MULTIPLE)
public interface ISaOutputFactory 
        extends IOutputFactory<SaDocument<ISaSpecification>>{

}
