// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tramoseats.proto

package demetra.tramoseats.io.protobuf;

public interface DecompositionSpecOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tramoseats.DecompositionSpec)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double xl_boundary = 1;</code>
   * @return The xlBoundary.
   */
  double getXlBoundary();

  /**
   * <code>.tramoseats.SeatsApproximation approximation = 2;</code>
   * @return The enum numeric value on the wire for approximation.
   */
  int getApproximationValue();
  /**
   * <code>.tramoseats.SeatsApproximation approximation = 2;</code>
   * @return The approximation.
   */
  demetra.tramoseats.io.protobuf.SeatsApproximation getApproximation();

  /**
   * <code>double seastolerance = 3;</code>
   * @return The seastolerance.
   */
  double getSeastolerance();

  /**
   * <code>double trend_boundary = 4;</code>
   * @return The trendBoundary.
   */
  double getTrendBoundary();

  /**
   * <code>double seas_boundary = 5;</code>
   * @return The seasBoundary.
   */
  double getSeasBoundary();

  /**
   * <code>double seas_boundary_at_pi = 6;</code>
   * @return The seasBoundaryAtPi.
   */
  double getSeasBoundaryAtPi();

  /**
   * <code>bool bias_correction = 7;</code>
   * @return The biasCorrection.
   */
  boolean getBiasCorrection();

  /**
   * <code>int32 nfcasts = 8;</code>
   * @return The nfcasts.
   */
  int getNfcasts();

  /**
   * <code>int32 nbcasts = 9;</code>
   * @return The nbcasts.
   */
  int getNbcasts();

  /**
   * <code>.tramoseats.SeatsAlgorithm algorithm = 10;</code>
   * @return The enum numeric value on the wire for algorithm.
   */
  int getAlgorithmValue();
  /**
   * <code>.tramoseats.SeatsAlgorithm algorithm = 10;</code>
   * @return The algorithm.
   */
  demetra.tramoseats.io.protobuf.SeatsAlgorithm getAlgorithm();
}
