// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tramoseats.proto

package demetra.tramoseats.io.protobuf;

/**
 * Protobuf enum {@code tramoseats.EasterType}
 */
public enum EasterType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>EASTER_UNUSED = 0;</code>
   */
  EASTER_UNUSED(0),
  /**
   * <code>EASTER_STANDARD = 1;</code>
   */
  EASTER_STANDARD(1),
  /**
   * <code>EASTER_INCLUDEEASTER = 2;</code>
   */
  EASTER_INCLUDEEASTER(2),
  /**
   * <code>EASTER_INCLUDEEASTERMONDAY = 3;</code>
   */
  EASTER_INCLUDEEASTERMONDAY(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>EASTER_UNUSED = 0;</code>
   */
  public static final int EASTER_UNUSED_VALUE = 0;
  /**
   * <code>EASTER_STANDARD = 1;</code>
   */
  public static final int EASTER_STANDARD_VALUE = 1;
  /**
   * <code>EASTER_INCLUDEEASTER = 2;</code>
   */
  public static final int EASTER_INCLUDEEASTER_VALUE = 2;
  /**
   * <code>EASTER_INCLUDEEASTERMONDAY = 3;</code>
   */
  public static final int EASTER_INCLUDEEASTERMONDAY_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static EasterType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static EasterType forNumber(int value) {
    switch (value) {
      case 0: return EASTER_UNUSED;
      case 1: return EASTER_STANDARD;
      case 2: return EASTER_INCLUDEEASTER;
      case 3: return EASTER_INCLUDEEASTERMONDAY;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<EasterType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      EasterType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<EasterType>() {
          public EasterType findValueByNumber(int number) {
            return EasterType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return demetra.tramoseats.io.protobuf.TramoSeatsProtos.getDescriptor().getEnumTypes().get(4);
  }

  private static final EasterType[] VALUES = values();

  public static EasterType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private EasterType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:tramoseats.EasterType)
}

