// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tramoseats.proto

package demetra.tramoseats.io.protobuf;

public interface SpecOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tramoseats.Spec)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.tramoseats.TramoSpec tramo = 1;</code>
   * @return Whether the tramo field is set.
   */
  boolean hasTramo();
  /**
   * <code>.tramoseats.TramoSpec tramo = 1;</code>
   * @return The tramo.
   */
  demetra.tramoseats.io.protobuf.TramoSpec getTramo();
  /**
   * <code>.tramoseats.TramoSpec tramo = 1;</code>
   */
  demetra.tramoseats.io.protobuf.TramoSpecOrBuilder getTramoOrBuilder();

  /**
   * <code>.tramoseats.DecompositionSpec seats = 2;</code>
   * @return Whether the seats field is set.
   */
  boolean hasSeats();
  /**
   * <code>.tramoseats.DecompositionSpec seats = 2;</code>
   * @return The seats.
   */
  demetra.tramoseats.io.protobuf.DecompositionSpec getSeats();
  /**
   * <code>.tramoseats.DecompositionSpec seats = 2;</code>
   */
  demetra.tramoseats.io.protobuf.DecompositionSpecOrBuilder getSeatsOrBuilder();

  /**
   * <code>.sa.BenchmarkingSpec benchmarking = 3;</code>
   * @return Whether the benchmarking field is set.
   */
  boolean hasBenchmarking();
  /**
   * <code>.sa.BenchmarkingSpec benchmarking = 3;</code>
   * @return The benchmarking.
   */
  demetra.sa.io.protobuf.SaProtos.BenchmarkingSpec getBenchmarking();
  /**
   * <code>.sa.BenchmarkingSpec benchmarking = 3;</code>
   */
  demetra.sa.io.protobuf.SaProtos.BenchmarkingSpecOrBuilder getBenchmarkingOrBuilder();
}
