// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tramoseats.proto

package demetra.tramoseats.io.protobuf;

/**
 * Protobuf enum {@code tramoseats.TradingDaysTest}
 */
public enum TradingDaysTest
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>TD_TEST_NO = 0;</code>
   */
  TD_TEST_NO(0),
  /**
   * <code>TD_TEST_SEPARATE_T = 1;</code>
   */
  TD_TEST_SEPARATE_T(1),
  /**
   * <code>TD_TEST_JOINT_F = 2;</code>
   */
  TD_TEST_JOINT_F(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>TD_TEST_NO = 0;</code>
   */
  public static final int TD_TEST_NO_VALUE = 0;
  /**
   * <code>TD_TEST_SEPARATE_T = 1;</code>
   */
  public static final int TD_TEST_SEPARATE_T_VALUE = 1;
  /**
   * <code>TD_TEST_JOINT_F = 2;</code>
   */
  public static final int TD_TEST_JOINT_F_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static TradingDaysTest valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static TradingDaysTest forNumber(int value) {
    switch (value) {
      case 0: return TD_TEST_NO;
      case 1: return TD_TEST_SEPARATE_T;
      case 2: return TD_TEST_JOINT_F;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<TradingDaysTest>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      TradingDaysTest> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<TradingDaysTest>() {
          public TradingDaysTest findValueByNumber(int number) {
            return TradingDaysTest.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return demetra.tramoseats.io.protobuf.TramoSeatsProtos.getDescriptor().getEnumTypes().get(3);
  }

  private static final TradingDaysTest[] VALUES = values();

  public static TradingDaysTest valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private TradingDaysTest(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:tramoseats.TradingDaysTest)
}

