// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tramoseats.proto

package demetra.tramoseats.io.protobuf;

/**
 * Protobuf type {@code tramoseats.TramoSeatsResults}
 */
public final class TramoSeatsResults extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tramoseats.TramoSeatsResults)
    TramoSeatsResultsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TramoSeatsResults.newBuilder() to construct.
  private TramoSeatsResults(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TramoSeatsResults() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TramoSeatsResults();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TramoSeatsResults(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            demetra.regarima.io.protobuf.RegArimaProtos.RegArimaModel.Builder subBuilder = null;
            if (preprocessing_ != null) {
              subBuilder = preprocessing_.toBuilder();
            }
            preprocessing_ = input.readMessage(demetra.regarima.io.protobuf.RegArimaProtos.RegArimaModel.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(preprocessing_);
              preprocessing_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            demetra.tramoseats.io.protobuf.SeatsResults.Builder subBuilder = null;
            if (decomposition_ != null) {
              subBuilder = decomposition_.toBuilder();
            }
            decomposition_ = input.readMessage(demetra.tramoseats.io.protobuf.SeatsResults.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(decomposition_);
              decomposition_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            demetra.sa.io.protobuf.SaProtos.SaDecomposition.Builder subBuilder = null;
            if (final_ != null) {
              subBuilder = final_.toBuilder();
            }
            final_ = input.readMessage(demetra.sa.io.protobuf.SaProtos.SaDecomposition.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(final_);
              final_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            demetra.sa.io.protobuf.SaProtos.Diagnostics.Builder subBuilder = null;
            if (diagnosticsSa_ != null) {
              subBuilder = diagnosticsSa_.toBuilder();
            }
            diagnosticsSa_ = input.readMessage(demetra.sa.io.protobuf.SaProtos.Diagnostics.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(diagnosticsSa_);
              diagnosticsSa_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return demetra.tramoseats.io.protobuf.TramoSeatsProtos.internal_static_tramoseats_TramoSeatsResults_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return demetra.tramoseats.io.protobuf.TramoSeatsProtos.internal_static_tramoseats_TramoSeatsResults_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            demetra.tramoseats.io.protobuf.TramoSeatsResults.class, demetra.tramoseats.io.protobuf.TramoSeatsResults.Builder.class);
  }

  public static final int PREPROCESSING_FIELD_NUMBER = 1;
  private demetra.regarima.io.protobuf.RegArimaProtos.RegArimaModel preprocessing_;
  /**
   * <code>.regarima.RegArimaModel preprocessing = 1;</code>
   * @return Whether the preprocessing field is set.
   */
  @java.lang.Override
  public boolean hasPreprocessing() {
    return preprocessing_ != null;
  }
  /**
   * <code>.regarima.RegArimaModel preprocessing = 1;</code>
   * @return The preprocessing.
   */
  @java.lang.Override
  public demetra.regarima.io.protobuf.RegArimaProtos.RegArimaModel getPreprocessing() {
    return preprocessing_ == null ? demetra.regarima.io.protobuf.RegArimaProtos.RegArimaModel.getDefaultInstance() : preprocessing_;
  }
  /**
   * <code>.regarima.RegArimaModel preprocessing = 1;</code>
   */
  @java.lang.Override
  public demetra.regarima.io.protobuf.RegArimaProtos.RegArimaModelOrBuilder getPreprocessingOrBuilder() {
    return getPreprocessing();
  }

  public static final int DECOMPOSITION_FIELD_NUMBER = 2;
  private demetra.tramoseats.io.protobuf.SeatsResults decomposition_;
  /**
   * <code>.tramoseats.SeatsResults decomposition = 2;</code>
   * @return Whether the decomposition field is set.
   */
  @java.lang.Override
  public boolean hasDecomposition() {
    return decomposition_ != null;
  }
  /**
   * <code>.tramoseats.SeatsResults decomposition = 2;</code>
   * @return The decomposition.
   */
  @java.lang.Override
  public demetra.tramoseats.io.protobuf.SeatsResults getDecomposition() {
    return decomposition_ == null ? demetra.tramoseats.io.protobuf.SeatsResults.getDefaultInstance() : decomposition_;
  }
  /**
   * <code>.tramoseats.SeatsResults decomposition = 2;</code>
   */
  @java.lang.Override
  public demetra.tramoseats.io.protobuf.SeatsResultsOrBuilder getDecompositionOrBuilder() {
    return getDecomposition();
  }

  public static final int FINAL_FIELD_NUMBER = 3;
  private demetra.sa.io.protobuf.SaProtos.SaDecomposition final_;
  /**
   * <code>.sa.SaDecomposition final = 3;</code>
   * @return Whether the final field is set.
   */
  @java.lang.Override
  public boolean hasFinal() {
    return final_ != null;
  }
  /**
   * <code>.sa.SaDecomposition final = 3;</code>
   * @return The final.
   */
  @java.lang.Override
  public demetra.sa.io.protobuf.SaProtos.SaDecomposition getFinal() {
    return final_ == null ? demetra.sa.io.protobuf.SaProtos.SaDecomposition.getDefaultInstance() : final_;
  }
  /**
   * <code>.sa.SaDecomposition final = 3;</code>
   */
  @java.lang.Override
  public demetra.sa.io.protobuf.SaProtos.SaDecompositionOrBuilder getFinalOrBuilder() {
    return getFinal();
  }

  public static final int DIAGNOSTICS_SA_FIELD_NUMBER = 5;
  private demetra.sa.io.protobuf.SaProtos.Diagnostics diagnosticsSa_;
  /**
   * <code>.sa.Diagnostics diagnostics_sa = 5;</code>
   * @return Whether the diagnosticsSa field is set.
   */
  @java.lang.Override
  public boolean hasDiagnosticsSa() {
    return diagnosticsSa_ != null;
  }
  /**
   * <code>.sa.Diagnostics diagnostics_sa = 5;</code>
   * @return The diagnosticsSa.
   */
  @java.lang.Override
  public demetra.sa.io.protobuf.SaProtos.Diagnostics getDiagnosticsSa() {
    return diagnosticsSa_ == null ? demetra.sa.io.protobuf.SaProtos.Diagnostics.getDefaultInstance() : diagnosticsSa_;
  }
  /**
   * <code>.sa.Diagnostics diagnostics_sa = 5;</code>
   */
  @java.lang.Override
  public demetra.sa.io.protobuf.SaProtos.DiagnosticsOrBuilder getDiagnosticsSaOrBuilder() {
    return getDiagnosticsSa();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (preprocessing_ != null) {
      output.writeMessage(1, getPreprocessing());
    }
    if (decomposition_ != null) {
      output.writeMessage(2, getDecomposition());
    }
    if (final_ != null) {
      output.writeMessage(3, getFinal());
    }
    if (diagnosticsSa_ != null) {
      output.writeMessage(5, getDiagnosticsSa());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (preprocessing_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getPreprocessing());
    }
    if (decomposition_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getDecomposition());
    }
    if (final_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getFinal());
    }
    if (diagnosticsSa_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getDiagnosticsSa());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof demetra.tramoseats.io.protobuf.TramoSeatsResults)) {
      return super.equals(obj);
    }
    demetra.tramoseats.io.protobuf.TramoSeatsResults other = (demetra.tramoseats.io.protobuf.TramoSeatsResults) obj;

    if (hasPreprocessing() != other.hasPreprocessing()) return false;
    if (hasPreprocessing()) {
      if (!getPreprocessing()
          .equals(other.getPreprocessing())) return false;
    }
    if (hasDecomposition() != other.hasDecomposition()) return false;
    if (hasDecomposition()) {
      if (!getDecomposition()
          .equals(other.getDecomposition())) return false;
    }
    if (hasFinal() != other.hasFinal()) return false;
    if (hasFinal()) {
      if (!getFinal()
          .equals(other.getFinal())) return false;
    }
    if (hasDiagnosticsSa() != other.hasDiagnosticsSa()) return false;
    if (hasDiagnosticsSa()) {
      if (!getDiagnosticsSa()
          .equals(other.getDiagnosticsSa())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPreprocessing()) {
      hash = (37 * hash) + PREPROCESSING_FIELD_NUMBER;
      hash = (53 * hash) + getPreprocessing().hashCode();
    }
    if (hasDecomposition()) {
      hash = (37 * hash) + DECOMPOSITION_FIELD_NUMBER;
      hash = (53 * hash) + getDecomposition().hashCode();
    }
    if (hasFinal()) {
      hash = (37 * hash) + FINAL_FIELD_NUMBER;
      hash = (53 * hash) + getFinal().hashCode();
    }
    if (hasDiagnosticsSa()) {
      hash = (37 * hash) + DIAGNOSTICS_SA_FIELD_NUMBER;
      hash = (53 * hash) + getDiagnosticsSa().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static demetra.tramoseats.io.protobuf.TramoSeatsResults parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static demetra.tramoseats.io.protobuf.TramoSeatsResults parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static demetra.tramoseats.io.protobuf.TramoSeatsResults parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static demetra.tramoseats.io.protobuf.TramoSeatsResults parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static demetra.tramoseats.io.protobuf.TramoSeatsResults parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static demetra.tramoseats.io.protobuf.TramoSeatsResults parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static demetra.tramoseats.io.protobuf.TramoSeatsResults parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static demetra.tramoseats.io.protobuf.TramoSeatsResults parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static demetra.tramoseats.io.protobuf.TramoSeatsResults parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static demetra.tramoseats.io.protobuf.TramoSeatsResults parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static demetra.tramoseats.io.protobuf.TramoSeatsResults parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static demetra.tramoseats.io.protobuf.TramoSeatsResults parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(demetra.tramoseats.io.protobuf.TramoSeatsResults prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tramoseats.TramoSeatsResults}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tramoseats.TramoSeatsResults)
      demetra.tramoseats.io.protobuf.TramoSeatsResultsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return demetra.tramoseats.io.protobuf.TramoSeatsProtos.internal_static_tramoseats_TramoSeatsResults_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return demetra.tramoseats.io.protobuf.TramoSeatsProtos.internal_static_tramoseats_TramoSeatsResults_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              demetra.tramoseats.io.protobuf.TramoSeatsResults.class, demetra.tramoseats.io.protobuf.TramoSeatsResults.Builder.class);
    }

    // Construct using demetra.tramoseats.io.protobuf.TramoSeatsResults.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (preprocessingBuilder_ == null) {
        preprocessing_ = null;
      } else {
        preprocessing_ = null;
        preprocessingBuilder_ = null;
      }
      if (decompositionBuilder_ == null) {
        decomposition_ = null;
      } else {
        decomposition_ = null;
        decompositionBuilder_ = null;
      }
      if (finalBuilder_ == null) {
        final_ = null;
      } else {
        final_ = null;
        finalBuilder_ = null;
      }
      if (diagnosticsSaBuilder_ == null) {
        diagnosticsSa_ = null;
      } else {
        diagnosticsSa_ = null;
        diagnosticsSaBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return demetra.tramoseats.io.protobuf.TramoSeatsProtos.internal_static_tramoseats_TramoSeatsResults_descriptor;
    }

    @java.lang.Override
    public demetra.tramoseats.io.protobuf.TramoSeatsResults getDefaultInstanceForType() {
      return demetra.tramoseats.io.protobuf.TramoSeatsResults.getDefaultInstance();
    }

    @java.lang.Override
    public demetra.tramoseats.io.protobuf.TramoSeatsResults build() {
      demetra.tramoseats.io.protobuf.TramoSeatsResults result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public demetra.tramoseats.io.protobuf.TramoSeatsResults buildPartial() {
      demetra.tramoseats.io.protobuf.TramoSeatsResults result = new demetra.tramoseats.io.protobuf.TramoSeatsResults(this);
      if (preprocessingBuilder_ == null) {
        result.preprocessing_ = preprocessing_;
      } else {
        result.preprocessing_ = preprocessingBuilder_.build();
      }
      if (decompositionBuilder_ == null) {
        result.decomposition_ = decomposition_;
      } else {
        result.decomposition_ = decompositionBuilder_.build();
      }
      if (finalBuilder_ == null) {
        result.final_ = final_;
      } else {
        result.final_ = finalBuilder_.build();
      }
      if (diagnosticsSaBuilder_ == null) {
        result.diagnosticsSa_ = diagnosticsSa_;
      } else {
        result.diagnosticsSa_ = diagnosticsSaBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof demetra.tramoseats.io.protobuf.TramoSeatsResults) {
        return mergeFrom((demetra.tramoseats.io.protobuf.TramoSeatsResults)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(demetra.tramoseats.io.protobuf.TramoSeatsResults other) {
      if (other == demetra.tramoseats.io.protobuf.TramoSeatsResults.getDefaultInstance()) return this;
      if (other.hasPreprocessing()) {
        mergePreprocessing(other.getPreprocessing());
      }
      if (other.hasDecomposition()) {
        mergeDecomposition(other.getDecomposition());
      }
      if (other.hasFinal()) {
        mergeFinal(other.getFinal());
      }
      if (other.hasDiagnosticsSa()) {
        mergeDiagnosticsSa(other.getDiagnosticsSa());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      demetra.tramoseats.io.protobuf.TramoSeatsResults parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (demetra.tramoseats.io.protobuf.TramoSeatsResults) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private demetra.regarima.io.protobuf.RegArimaProtos.RegArimaModel preprocessing_;
    private com.google.protobuf.SingleFieldBuilderV3<
        demetra.regarima.io.protobuf.RegArimaProtos.RegArimaModel, demetra.regarima.io.protobuf.RegArimaProtos.RegArimaModel.Builder, demetra.regarima.io.protobuf.RegArimaProtos.RegArimaModelOrBuilder> preprocessingBuilder_;
    /**
     * <code>.regarima.RegArimaModel preprocessing = 1;</code>
     * @return Whether the preprocessing field is set.
     */
    public boolean hasPreprocessing() {
      return preprocessingBuilder_ != null || preprocessing_ != null;
    }
    /**
     * <code>.regarima.RegArimaModel preprocessing = 1;</code>
     * @return The preprocessing.
     */
    public demetra.regarima.io.protobuf.RegArimaProtos.RegArimaModel getPreprocessing() {
      if (preprocessingBuilder_ == null) {
        return preprocessing_ == null ? demetra.regarima.io.protobuf.RegArimaProtos.RegArimaModel.getDefaultInstance() : preprocessing_;
      } else {
        return preprocessingBuilder_.getMessage();
      }
    }
    /**
     * <code>.regarima.RegArimaModel preprocessing = 1;</code>
     */
    public Builder setPreprocessing(demetra.regarima.io.protobuf.RegArimaProtos.RegArimaModel value) {
      if (preprocessingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        preprocessing_ = value;
        onChanged();
      } else {
        preprocessingBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.regarima.RegArimaModel preprocessing = 1;</code>
     */
    public Builder setPreprocessing(
        demetra.regarima.io.protobuf.RegArimaProtos.RegArimaModel.Builder builderForValue) {
      if (preprocessingBuilder_ == null) {
        preprocessing_ = builderForValue.build();
        onChanged();
      } else {
        preprocessingBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.regarima.RegArimaModel preprocessing = 1;</code>
     */
    public Builder mergePreprocessing(demetra.regarima.io.protobuf.RegArimaProtos.RegArimaModel value) {
      if (preprocessingBuilder_ == null) {
        if (preprocessing_ != null) {
          preprocessing_ =
            demetra.regarima.io.protobuf.RegArimaProtos.RegArimaModel.newBuilder(preprocessing_).mergeFrom(value).buildPartial();
        } else {
          preprocessing_ = value;
        }
        onChanged();
      } else {
        preprocessingBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.regarima.RegArimaModel preprocessing = 1;</code>
     */
    public Builder clearPreprocessing() {
      if (preprocessingBuilder_ == null) {
        preprocessing_ = null;
        onChanged();
      } else {
        preprocessing_ = null;
        preprocessingBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.regarima.RegArimaModel preprocessing = 1;</code>
     */
    public demetra.regarima.io.protobuf.RegArimaProtos.RegArimaModel.Builder getPreprocessingBuilder() {
      
      onChanged();
      return getPreprocessingFieldBuilder().getBuilder();
    }
    /**
     * <code>.regarima.RegArimaModel preprocessing = 1;</code>
     */
    public demetra.regarima.io.protobuf.RegArimaProtos.RegArimaModelOrBuilder getPreprocessingOrBuilder() {
      if (preprocessingBuilder_ != null) {
        return preprocessingBuilder_.getMessageOrBuilder();
      } else {
        return preprocessing_ == null ?
            demetra.regarima.io.protobuf.RegArimaProtos.RegArimaModel.getDefaultInstance() : preprocessing_;
      }
    }
    /**
     * <code>.regarima.RegArimaModel preprocessing = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        demetra.regarima.io.protobuf.RegArimaProtos.RegArimaModel, demetra.regarima.io.protobuf.RegArimaProtos.RegArimaModel.Builder, demetra.regarima.io.protobuf.RegArimaProtos.RegArimaModelOrBuilder> 
        getPreprocessingFieldBuilder() {
      if (preprocessingBuilder_ == null) {
        preprocessingBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            demetra.regarima.io.protobuf.RegArimaProtos.RegArimaModel, demetra.regarima.io.protobuf.RegArimaProtos.RegArimaModel.Builder, demetra.regarima.io.protobuf.RegArimaProtos.RegArimaModelOrBuilder>(
                getPreprocessing(),
                getParentForChildren(),
                isClean());
        preprocessing_ = null;
      }
      return preprocessingBuilder_;
    }

    private demetra.tramoseats.io.protobuf.SeatsResults decomposition_;
    private com.google.protobuf.SingleFieldBuilderV3<
        demetra.tramoseats.io.protobuf.SeatsResults, demetra.tramoseats.io.protobuf.SeatsResults.Builder, demetra.tramoseats.io.protobuf.SeatsResultsOrBuilder> decompositionBuilder_;
    /**
     * <code>.tramoseats.SeatsResults decomposition = 2;</code>
     * @return Whether the decomposition field is set.
     */
    public boolean hasDecomposition() {
      return decompositionBuilder_ != null || decomposition_ != null;
    }
    /**
     * <code>.tramoseats.SeatsResults decomposition = 2;</code>
     * @return The decomposition.
     */
    public demetra.tramoseats.io.protobuf.SeatsResults getDecomposition() {
      if (decompositionBuilder_ == null) {
        return decomposition_ == null ? demetra.tramoseats.io.protobuf.SeatsResults.getDefaultInstance() : decomposition_;
      } else {
        return decompositionBuilder_.getMessage();
      }
    }
    /**
     * <code>.tramoseats.SeatsResults decomposition = 2;</code>
     */
    public Builder setDecomposition(demetra.tramoseats.io.protobuf.SeatsResults value) {
      if (decompositionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        decomposition_ = value;
        onChanged();
      } else {
        decompositionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.tramoseats.SeatsResults decomposition = 2;</code>
     */
    public Builder setDecomposition(
        demetra.tramoseats.io.protobuf.SeatsResults.Builder builderForValue) {
      if (decompositionBuilder_ == null) {
        decomposition_ = builderForValue.build();
        onChanged();
      } else {
        decompositionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.tramoseats.SeatsResults decomposition = 2;</code>
     */
    public Builder mergeDecomposition(demetra.tramoseats.io.protobuf.SeatsResults value) {
      if (decompositionBuilder_ == null) {
        if (decomposition_ != null) {
          decomposition_ =
            demetra.tramoseats.io.protobuf.SeatsResults.newBuilder(decomposition_).mergeFrom(value).buildPartial();
        } else {
          decomposition_ = value;
        }
        onChanged();
      } else {
        decompositionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.tramoseats.SeatsResults decomposition = 2;</code>
     */
    public Builder clearDecomposition() {
      if (decompositionBuilder_ == null) {
        decomposition_ = null;
        onChanged();
      } else {
        decomposition_ = null;
        decompositionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.tramoseats.SeatsResults decomposition = 2;</code>
     */
    public demetra.tramoseats.io.protobuf.SeatsResults.Builder getDecompositionBuilder() {
      
      onChanged();
      return getDecompositionFieldBuilder().getBuilder();
    }
    /**
     * <code>.tramoseats.SeatsResults decomposition = 2;</code>
     */
    public demetra.tramoseats.io.protobuf.SeatsResultsOrBuilder getDecompositionOrBuilder() {
      if (decompositionBuilder_ != null) {
        return decompositionBuilder_.getMessageOrBuilder();
      } else {
        return decomposition_ == null ?
            demetra.tramoseats.io.protobuf.SeatsResults.getDefaultInstance() : decomposition_;
      }
    }
    /**
     * <code>.tramoseats.SeatsResults decomposition = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        demetra.tramoseats.io.protobuf.SeatsResults, demetra.tramoseats.io.protobuf.SeatsResults.Builder, demetra.tramoseats.io.protobuf.SeatsResultsOrBuilder> 
        getDecompositionFieldBuilder() {
      if (decompositionBuilder_ == null) {
        decompositionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            demetra.tramoseats.io.protobuf.SeatsResults, demetra.tramoseats.io.protobuf.SeatsResults.Builder, demetra.tramoseats.io.protobuf.SeatsResultsOrBuilder>(
                getDecomposition(),
                getParentForChildren(),
                isClean());
        decomposition_ = null;
      }
      return decompositionBuilder_;
    }

    private demetra.sa.io.protobuf.SaProtos.SaDecomposition final_;
    private com.google.protobuf.SingleFieldBuilderV3<
        demetra.sa.io.protobuf.SaProtos.SaDecomposition, demetra.sa.io.protobuf.SaProtos.SaDecomposition.Builder, demetra.sa.io.protobuf.SaProtos.SaDecompositionOrBuilder> finalBuilder_;
    /**
     * <code>.sa.SaDecomposition final = 3;</code>
     * @return Whether the final field is set.
     */
    public boolean hasFinal() {
      return finalBuilder_ != null || final_ != null;
    }
    /**
     * <code>.sa.SaDecomposition final = 3;</code>
     * @return The final.
     */
    public demetra.sa.io.protobuf.SaProtos.SaDecomposition getFinal() {
      if (finalBuilder_ == null) {
        return final_ == null ? demetra.sa.io.protobuf.SaProtos.SaDecomposition.getDefaultInstance() : final_;
      } else {
        return finalBuilder_.getMessage();
      }
    }
    /**
     * <code>.sa.SaDecomposition final = 3;</code>
     */
    public Builder setFinal(demetra.sa.io.protobuf.SaProtos.SaDecomposition value) {
      if (finalBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        final_ = value;
        onChanged();
      } else {
        finalBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.sa.SaDecomposition final = 3;</code>
     */
    public Builder setFinal(
        demetra.sa.io.protobuf.SaProtos.SaDecomposition.Builder builderForValue) {
      if (finalBuilder_ == null) {
        final_ = builderForValue.build();
        onChanged();
      } else {
        finalBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.sa.SaDecomposition final = 3;</code>
     */
    public Builder mergeFinal(demetra.sa.io.protobuf.SaProtos.SaDecomposition value) {
      if (finalBuilder_ == null) {
        if (final_ != null) {
          final_ =
            demetra.sa.io.protobuf.SaProtos.SaDecomposition.newBuilder(final_).mergeFrom(value).buildPartial();
        } else {
          final_ = value;
        }
        onChanged();
      } else {
        finalBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.sa.SaDecomposition final = 3;</code>
     */
    public Builder clearFinal() {
      if (finalBuilder_ == null) {
        final_ = null;
        onChanged();
      } else {
        final_ = null;
        finalBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.sa.SaDecomposition final = 3;</code>
     */
    public demetra.sa.io.protobuf.SaProtos.SaDecomposition.Builder getFinalBuilder() {
      
      onChanged();
      return getFinalFieldBuilder().getBuilder();
    }
    /**
     * <code>.sa.SaDecomposition final = 3;</code>
     */
    public demetra.sa.io.protobuf.SaProtos.SaDecompositionOrBuilder getFinalOrBuilder() {
      if (finalBuilder_ != null) {
        return finalBuilder_.getMessageOrBuilder();
      } else {
        return final_ == null ?
            demetra.sa.io.protobuf.SaProtos.SaDecomposition.getDefaultInstance() : final_;
      }
    }
    /**
     * <code>.sa.SaDecomposition final = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        demetra.sa.io.protobuf.SaProtos.SaDecomposition, demetra.sa.io.protobuf.SaProtos.SaDecomposition.Builder, demetra.sa.io.protobuf.SaProtos.SaDecompositionOrBuilder> 
        getFinalFieldBuilder() {
      if (finalBuilder_ == null) {
        finalBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            demetra.sa.io.protobuf.SaProtos.SaDecomposition, demetra.sa.io.protobuf.SaProtos.SaDecomposition.Builder, demetra.sa.io.protobuf.SaProtos.SaDecompositionOrBuilder>(
                getFinal(),
                getParentForChildren(),
                isClean());
        final_ = null;
      }
      return finalBuilder_;
    }

    private demetra.sa.io.protobuf.SaProtos.Diagnostics diagnosticsSa_;
    private com.google.protobuf.SingleFieldBuilderV3<
        demetra.sa.io.protobuf.SaProtos.Diagnostics, demetra.sa.io.protobuf.SaProtos.Diagnostics.Builder, demetra.sa.io.protobuf.SaProtos.DiagnosticsOrBuilder> diagnosticsSaBuilder_;
    /**
     * <code>.sa.Diagnostics diagnostics_sa = 5;</code>
     * @return Whether the diagnosticsSa field is set.
     */
    public boolean hasDiagnosticsSa() {
      return diagnosticsSaBuilder_ != null || diagnosticsSa_ != null;
    }
    /**
     * <code>.sa.Diagnostics diagnostics_sa = 5;</code>
     * @return The diagnosticsSa.
     */
    public demetra.sa.io.protobuf.SaProtos.Diagnostics getDiagnosticsSa() {
      if (diagnosticsSaBuilder_ == null) {
        return diagnosticsSa_ == null ? demetra.sa.io.protobuf.SaProtos.Diagnostics.getDefaultInstance() : diagnosticsSa_;
      } else {
        return diagnosticsSaBuilder_.getMessage();
      }
    }
    /**
     * <code>.sa.Diagnostics diagnostics_sa = 5;</code>
     */
    public Builder setDiagnosticsSa(demetra.sa.io.protobuf.SaProtos.Diagnostics value) {
      if (diagnosticsSaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        diagnosticsSa_ = value;
        onChanged();
      } else {
        diagnosticsSaBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.sa.Diagnostics diagnostics_sa = 5;</code>
     */
    public Builder setDiagnosticsSa(
        demetra.sa.io.protobuf.SaProtos.Diagnostics.Builder builderForValue) {
      if (diagnosticsSaBuilder_ == null) {
        diagnosticsSa_ = builderForValue.build();
        onChanged();
      } else {
        diagnosticsSaBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.sa.Diagnostics diagnostics_sa = 5;</code>
     */
    public Builder mergeDiagnosticsSa(demetra.sa.io.protobuf.SaProtos.Diagnostics value) {
      if (diagnosticsSaBuilder_ == null) {
        if (diagnosticsSa_ != null) {
          diagnosticsSa_ =
            demetra.sa.io.protobuf.SaProtos.Diagnostics.newBuilder(diagnosticsSa_).mergeFrom(value).buildPartial();
        } else {
          diagnosticsSa_ = value;
        }
        onChanged();
      } else {
        diagnosticsSaBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.sa.Diagnostics diagnostics_sa = 5;</code>
     */
    public Builder clearDiagnosticsSa() {
      if (diagnosticsSaBuilder_ == null) {
        diagnosticsSa_ = null;
        onChanged();
      } else {
        diagnosticsSa_ = null;
        diagnosticsSaBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.sa.Diagnostics diagnostics_sa = 5;</code>
     */
    public demetra.sa.io.protobuf.SaProtos.Diagnostics.Builder getDiagnosticsSaBuilder() {
      
      onChanged();
      return getDiagnosticsSaFieldBuilder().getBuilder();
    }
    /**
     * <code>.sa.Diagnostics diagnostics_sa = 5;</code>
     */
    public demetra.sa.io.protobuf.SaProtos.DiagnosticsOrBuilder getDiagnosticsSaOrBuilder() {
      if (diagnosticsSaBuilder_ != null) {
        return diagnosticsSaBuilder_.getMessageOrBuilder();
      } else {
        return diagnosticsSa_ == null ?
            demetra.sa.io.protobuf.SaProtos.Diagnostics.getDefaultInstance() : diagnosticsSa_;
      }
    }
    /**
     * <code>.sa.Diagnostics diagnostics_sa = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        demetra.sa.io.protobuf.SaProtos.Diagnostics, demetra.sa.io.protobuf.SaProtos.Diagnostics.Builder, demetra.sa.io.protobuf.SaProtos.DiagnosticsOrBuilder> 
        getDiagnosticsSaFieldBuilder() {
      if (diagnosticsSaBuilder_ == null) {
        diagnosticsSaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            demetra.sa.io.protobuf.SaProtos.Diagnostics, demetra.sa.io.protobuf.SaProtos.Diagnostics.Builder, demetra.sa.io.protobuf.SaProtos.DiagnosticsOrBuilder>(
                getDiagnosticsSa(),
                getParentForChildren(),
                isClean());
        diagnosticsSa_ = null;
      }
      return diagnosticsSaBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tramoseats.TramoSeatsResults)
  }

  // @@protoc_insertion_point(class_scope:tramoseats.TramoSeatsResults)
  private static final demetra.tramoseats.io.protobuf.TramoSeatsResults DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new demetra.tramoseats.io.protobuf.TramoSeatsResults();
  }

  public static demetra.tramoseats.io.protobuf.TramoSeatsResults getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TramoSeatsResults>
      PARSER = new com.google.protobuf.AbstractParser<TramoSeatsResults>() {
    @java.lang.Override
    public TramoSeatsResults parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TramoSeatsResults(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TramoSeatsResults> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TramoSeatsResults> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public demetra.tramoseats.io.protobuf.TramoSeatsResults getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

