/*
 * Copyright 2017 National Bank of Belgium
 * 
 * Licensed under the EUPL, Version 1.2 or – as soon they will be approved 
 * by the European Commission - subsequent versions of the EUPL (the "Licence");
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 * 
 * https://joinup.ec.europa.eu/software/page/eupl
 * 
 * Unless required by applicable law or agreed to in writing, software 
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and 
 * limitations under the Licence.
 */
package demetra.dstats;

import demetra.data.DataBlock;
import demetra.data.DoubleSequence;
import demetra.design.Development;
import demetra.design.Immutable;
import demetra.maths.Constants;
import demetra.maths.matrices.LowerTriangularMatrix;
import demetra.maths.matrices.Matrix;
import demetra.maths.matrices.SymmetricMatrix;
import demetra.random.IRandomNumberGenerator;
import lombok.NonNull;

/**
 *
 * @author Jean Palate
 */
@Development(status = Development.Status.Release)
@Immutable
public class MultivariateNormal {
    
    private static final Normal N=new Normal(0,1);

    private final DataBlock mean;
    private final Matrix cov;
    private volatile Matrix lchol;

    public MultivariateNormal(DoubleSequence mean, Matrix cov) {
        this.mean = DataBlock.copyOf(mean);
        this.cov = cov.deepClone();
    }

    /**
     * @return the mean
     */
    public DataBlock getMean() {
        return mean;
    }

    /**
     * @return the cov
     */
    public Matrix getCovariance() {
        return cov;
    }

    public int getDimension() {
        return mean.length();
    }

    /**
     * Fills the given datablock by randoms generated by the random generator
     * @param rng
     * @param rnd The buffer that will contain the generated random numbers
     */
    public void random(@NonNull IRandomNumberGenerator rng, DataBlock rnd) {
        rnd.set(()->N.random(rng));
        Matrix lm=l();
        LowerTriangularMatrix.lmul(lm, rnd);
        rnd.add(mean);
    }
    
    private Matrix l(){
        Matrix tmp = this.lchol;
        if (tmp == null) {
            synchronized (this) {
                tmp = this.lchol;
                if (tmp == null) {
                    tmp=cov.deepClone();
                    SymmetricMatrix.lcholesky(tmp, Constants.getEpsilon());
                    this.lchol = tmp;
                }
            }
        }
        return lchol;
    }

}
