/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demetra.timeseries.regression;

/**
 * Variables automatically generated by the system
 * @author PALATEJ
 */
public interface ISystemVariable extends ITsVariable{
    
}
