// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: x13.proto

package demetra.x13.io.protobuf;

public interface MStatisticsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:x13.MStatistics)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double m1 = 1;</code>
   * @return The m1.
   */
  double getM1();

  /**
   * <code>double m2 = 2;</code>
   * @return The m2.
   */
  double getM2();

  /**
   * <code>double m3 = 3;</code>
   * @return The m3.
   */
  double getM3();

  /**
   * <code>double m4 = 4;</code>
   * @return The m4.
   */
  double getM4();

  /**
   * <code>double m5 = 5;</code>
   * @return The m5.
   */
  double getM5();

  /**
   * <code>double m6 = 6;</code>
   * @return The m6.
   */
  double getM6();

  /**
   * <code>double m7 = 7;</code>
   * @return The m7.
   */
  double getM7();

  /**
   * <code>double m8 = 8;</code>
   * @return The m8.
   */
  double getM8();

  /**
   * <code>double m9 = 9;</code>
   * @return The m9.
   */
  double getM9();

  /**
   * <code>double m10 = 10;</code>
   * @return The m10.
   */
  double getM10();

  /**
   * <code>double m11 = 11;</code>
   * @return The m11.
   */
  double getM11();

  /**
   * <code>double q = 12;</code>
   * @return The q.
   */
  double getQ();

  /**
   * <code>double qm2 = 13;</code>
   * @return The qm2.
   */
  double getQm2();
}
