// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: x13.proto

package demetra.x13.io.protobuf;

/**
 * Protobuf enum {@code x13.RegressionTest}
 */
public enum RegressionTest
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>TEST_NO = 0;</code>
   */
  TEST_NO(0),
  /**
   * <code>TEST_ADD = 1;</code>
   */
  TEST_ADD(1),
  /**
   * <code>TEST_REMOVE = 2;</code>
   */
  TEST_REMOVE(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>TEST_NO = 0;</code>
   */
  public static final int TEST_NO_VALUE = 0;
  /**
   * <code>TEST_ADD = 1;</code>
   */
  public static final int TEST_ADD_VALUE = 1;
  /**
   * <code>TEST_REMOVE = 2;</code>
   */
  public static final int TEST_REMOVE_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static RegressionTest valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static RegressionTest forNumber(int value) {
    switch (value) {
      case 0: return TEST_NO;
      case 1: return TEST_ADD;
      case 2: return TEST_REMOVE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<RegressionTest>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      RegressionTest> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<RegressionTest>() {
          public RegressionTest findValueByNumber(int number) {
            return RegressionTest.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return demetra.x13.io.protobuf.X13Protos.getDescriptor().getEnumTypes().get(6);
  }

  private static final RegressionTest[] VALUES = values();

  public static RegressionTest valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private RegressionTest(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:x13.RegressionTest)
}

