// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: x13.proto

package demetra.x13.io.protobuf;

/**
 * Protobuf enum {@code x13.SeasonalFilter}
 */
public enum SeasonalFilter
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>SEASONAL_FILTER_MSR = 0;</code>
   */
  SEASONAL_FILTER_MSR(0),
  /**
   * <code>SEASONAL_FILTER_S3X1 = 1;</code>
   */
  SEASONAL_FILTER_S3X1(1),
  /**
   * <code>SEASONAL_FILTER_S3X3 = 2;</code>
   */
  SEASONAL_FILTER_S3X3(2),
  /**
   * <code>SEASONAL_FILTER_S3X5 = 3;</code>
   */
  SEASONAL_FILTER_S3X5(3),
  /**
   * <code>SEASONAL_FILTER_S3X9 = 4;</code>
   */
  SEASONAL_FILTER_S3X9(4),
  /**
   * <code>SEASONAL_FILTER_S3X15 = 5;</code>
   */
  SEASONAL_FILTER_S3X15(5),
  /**
   * <code>SEASONAL_FILTER_STABLE = 6;</code>
   */
  SEASONAL_FILTER_STABLE(6),
  /**
   * <code>SEASONAL_FILTER_X11DEFAULT = 7;</code>
   */
  SEASONAL_FILTER_X11DEFAULT(7),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>SEASONAL_FILTER_MSR = 0;</code>
   */
  public static final int SEASONAL_FILTER_MSR_VALUE = 0;
  /**
   * <code>SEASONAL_FILTER_S3X1 = 1;</code>
   */
  public static final int SEASONAL_FILTER_S3X1_VALUE = 1;
  /**
   * <code>SEASONAL_FILTER_S3X3 = 2;</code>
   */
  public static final int SEASONAL_FILTER_S3X3_VALUE = 2;
  /**
   * <code>SEASONAL_FILTER_S3X5 = 3;</code>
   */
  public static final int SEASONAL_FILTER_S3X5_VALUE = 3;
  /**
   * <code>SEASONAL_FILTER_S3X9 = 4;</code>
   */
  public static final int SEASONAL_FILTER_S3X9_VALUE = 4;
  /**
   * <code>SEASONAL_FILTER_S3X15 = 5;</code>
   */
  public static final int SEASONAL_FILTER_S3X15_VALUE = 5;
  /**
   * <code>SEASONAL_FILTER_STABLE = 6;</code>
   */
  public static final int SEASONAL_FILTER_STABLE_VALUE = 6;
  /**
   * <code>SEASONAL_FILTER_X11DEFAULT = 7;</code>
   */
  public static final int SEASONAL_FILTER_X11DEFAULT_VALUE = 7;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static SeasonalFilter valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static SeasonalFilter forNumber(int value) {
    switch (value) {
      case 0: return SEASONAL_FILTER_MSR;
      case 1: return SEASONAL_FILTER_S3X1;
      case 2: return SEASONAL_FILTER_S3X3;
      case 3: return SEASONAL_FILTER_S3X5;
      case 4: return SEASONAL_FILTER_S3X9;
      case 5: return SEASONAL_FILTER_S3X15;
      case 6: return SEASONAL_FILTER_STABLE;
      case 7: return SEASONAL_FILTER_X11DEFAULT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<SeasonalFilter>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      SeasonalFilter> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<SeasonalFilter>() {
          public SeasonalFilter findValueByNumber(int number) {
            return SeasonalFilter.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return demetra.x13.io.protobuf.X13Protos.getDescriptor().getEnumTypes().get(1);
  }

  private static final SeasonalFilter[] VALUES = values();

  public static SeasonalFilter valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private SeasonalFilter(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:x13.SeasonalFilter)
}

