// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: x13.proto

package demetra.x13.io.protobuf;

public interface X11SpecOrBuilder extends
    // @@protoc_insertion_point(interface_extends:x13.X11Spec)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.x13.DecompositionMode mode = 1;</code>
   * @return The enum numeric value on the wire for mode.
   */
  int getModeValue();
  /**
   * <code>.x13.DecompositionMode mode = 1;</code>
   * @return The mode.
   */
  demetra.x13.io.protobuf.DecompositionMode getMode();

  /**
   * <code>bool seasonal = 2;</code>
   * @return The seasonal.
   */
  boolean getSeasonal();

  /**
   * <code>int32 henderson = 3;</code>
   * @return The henderson.
   */
  int getHenderson();

  /**
   * <code>repeated .x13.SeasonalFilter sfilters = 4;</code>
   * @return A list containing the sfilters.
   */
  java.util.List<demetra.x13.io.protobuf.SeasonalFilter> getSfiltersList();
  /**
   * <code>repeated .x13.SeasonalFilter sfilters = 4;</code>
   * @return The count of sfilters.
   */
  int getSfiltersCount();
  /**
   * <code>repeated .x13.SeasonalFilter sfilters = 4;</code>
   * @param index The index of the element to return.
   * @return The sfilters at the given index.
   */
  demetra.x13.io.protobuf.SeasonalFilter getSfilters(int index);
  /**
   * <code>repeated .x13.SeasonalFilter sfilters = 4;</code>
   * @return A list containing the enum numeric values on the wire for sfilters.
   */
  java.util.List<java.lang.Integer>
  getSfiltersValueList();
  /**
   * <code>repeated .x13.SeasonalFilter sfilters = 4;</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of sfilters at the given index.
   */
  int getSfiltersValue(int index);

  /**
   * <code>double lsig = 5;</code>
   * @return The lsig.
   */
  double getLsig();

  /**
   * <code>double usig = 6;</code>
   * @return The usig.
   */
  double getUsig();

  /**
   * <code>int32 nfcasts = 7;</code>
   * @return The nfcasts.
   */
  int getNfcasts();

  /**
   * <code>int32 nbcasts = 8;</code>
   * @return The nbcasts.
   */
  int getNbcasts();

  /**
   * <code>.x13.CalendarSigma sigma = 9;</code>
   * @return The enum numeric value on the wire for sigma.
   */
  int getSigmaValue();
  /**
   * <code>.x13.CalendarSigma sigma = 9;</code>
   * @return The sigma.
   */
  demetra.x13.io.protobuf.CalendarSigma getSigma();

  /**
   * <code>repeated int32 vsigmas = 10;</code>
   * @return A list containing the vsigmas.
   */
  java.util.List<java.lang.Integer> getVsigmasList();
  /**
   * <code>repeated int32 vsigmas = 10;</code>
   * @return The count of vsigmas.
   */
  int getVsigmasCount();
  /**
   * <code>repeated int32 vsigmas = 10;</code>
   * @param index The index of the element to return.
   * @return The vsigmas at the given index.
   */
  int getVsigmas(int index);

  /**
   * <code>bool exclude_fcasts = 11;</code>
   * @return The excludeFcasts.
   */
  boolean getExcludeFcasts();

  /**
   * <code>.x13.BiasCorrection bias = 12;</code>
   * @return The enum numeric value on the wire for bias.
   */
  int getBiasValue();
  /**
   * <code>.x13.BiasCorrection bias = 12;</code>
   * @return The bias.
   */
  demetra.x13.io.protobuf.BiasCorrection getBias();
}
