// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: x13.proto

package demetra.x13.io.protobuf;

public interface X13FinalsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:x13.X13Finals)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.jd3.TsData d11final = 1;</code>
   * @return Whether the d11final field is set.
   */
  boolean hasD11Final();
  /**
   * <code>.jd3.TsData d11final = 1;</code>
   * @return The d11final.
   */
  demetra.toolkit.io.protobuf.ToolkitProtos.TsData getD11Final();
  /**
   * <code>.jd3.TsData d11final = 1;</code>
   */
  demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder getD11FinalOrBuilder();

  /**
   * <code>.jd3.TsData d12final = 2;</code>
   * @return Whether the d12final field is set.
   */
  boolean hasD12Final();
  /**
   * <code>.jd3.TsData d12final = 2;</code>
   * @return The d12final.
   */
  demetra.toolkit.io.protobuf.ToolkitProtos.TsData getD12Final();
  /**
   * <code>.jd3.TsData d12final = 2;</code>
   */
  demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder getD12FinalOrBuilder();

  /**
   * <code>.jd3.TsData d13final = 3;</code>
   * @return Whether the d13final field is set.
   */
  boolean hasD13Final();
  /**
   * <code>.jd3.TsData d13final = 3;</code>
   * @return The d13final.
   */
  demetra.toolkit.io.protobuf.ToolkitProtos.TsData getD13Final();
  /**
   * <code>.jd3.TsData d13final = 3;</code>
   */
  demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder getD13FinalOrBuilder();

  /**
   * <code>.jd3.TsData d16 = 4;</code>
   * @return Whether the d16 field is set.
   */
  boolean hasD16();
  /**
   * <code>.jd3.TsData d16 = 4;</code>
   * @return The d16.
   */
  demetra.toolkit.io.protobuf.ToolkitProtos.TsData getD16();
  /**
   * <code>.jd3.TsData d16 = 4;</code>
   */
  demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder getD16OrBuilder();

  /**
   * <code>.jd3.TsData d18 = 5;</code>
   * @return Whether the d18 field is set.
   */
  boolean hasD18();
  /**
   * <code>.jd3.TsData d18 = 5;</code>
   * @return The d18.
   */
  demetra.toolkit.io.protobuf.ToolkitProtos.TsData getD18();
  /**
   * <code>.jd3.TsData d18 = 5;</code>
   */
  demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder getD18OrBuilder();

  /**
   * <code>.jd3.TsData d11a = 6;</code>
   * @return Whether the d11a field is set.
   */
  boolean hasD11A();
  /**
   * <code>.jd3.TsData d11a = 6;</code>
   * @return The d11a.
   */
  demetra.toolkit.io.protobuf.ToolkitProtos.TsData getD11A();
  /**
   * <code>.jd3.TsData d11a = 6;</code>
   */
  demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder getD11AOrBuilder();

  /**
   * <code>.jd3.TsData d12a = 7;</code>
   * @return Whether the d12a field is set.
   */
  boolean hasD12A();
  /**
   * <code>.jd3.TsData d12a = 7;</code>
   * @return The d12a.
   */
  demetra.toolkit.io.protobuf.ToolkitProtos.TsData getD12A();
  /**
   * <code>.jd3.TsData d12a = 7;</code>
   */
  demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder getD12AOrBuilder();

  /**
   * <code>.jd3.TsData d16a = 8;</code>
   * @return Whether the d16a field is set.
   */
  boolean hasD16A();
  /**
   * <code>.jd3.TsData d16a = 8;</code>
   * @return The d16a.
   */
  demetra.toolkit.io.protobuf.ToolkitProtos.TsData getD16A();
  /**
   * <code>.jd3.TsData d16a = 8;</code>
   */
  demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder getD16AOrBuilder();

  /**
   * <code>.jd3.TsData d18a = 9;</code>
   * @return Whether the d18a field is set.
   */
  boolean hasD18A();
  /**
   * <code>.jd3.TsData d18a = 9;</code>
   * @return The d18a.
   */
  demetra.toolkit.io.protobuf.ToolkitProtos.TsData getD18A();
  /**
   * <code>.jd3.TsData d18a = 9;</code>
   */
  demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder getD18AOrBuilder();

  /**
   * <code>.jd3.TsData e1 = 10;</code>
   * @return Whether the e1 field is set.
   */
  boolean hasE1();
  /**
   * <code>.jd3.TsData e1 = 10;</code>
   * @return The e1.
   */
  demetra.toolkit.io.protobuf.ToolkitProtos.TsData getE1();
  /**
   * <code>.jd3.TsData e1 = 10;</code>
   */
  demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder getE1OrBuilder();

  /**
   * <code>.jd3.TsData e2 = 11;</code>
   * @return Whether the e2 field is set.
   */
  boolean hasE2();
  /**
   * <code>.jd3.TsData e2 = 11;</code>
   * @return The e2.
   */
  demetra.toolkit.io.protobuf.ToolkitProtos.TsData getE2();
  /**
   * <code>.jd3.TsData e2 = 11;</code>
   */
  demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder getE2OrBuilder();

  /**
   * <code>.jd3.TsData e3 = 12;</code>
   * @return Whether the e3 field is set.
   */
  boolean hasE3();
  /**
   * <code>.jd3.TsData e3 = 12;</code>
   * @return The e3.
   */
  demetra.toolkit.io.protobuf.ToolkitProtos.TsData getE3();
  /**
   * <code>.jd3.TsData e3 = 12;</code>
   */
  demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder getE3OrBuilder();

  /**
   * <code>.jd3.TsData e11 = 13;</code>
   * @return Whether the e11 field is set.
   */
  boolean hasE11();
  /**
   * <code>.jd3.TsData e11 = 13;</code>
   * @return The e11.
   */
  demetra.toolkit.io.protobuf.ToolkitProtos.TsData getE11();
  /**
   * <code>.jd3.TsData e11 = 13;</code>
   */
  demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder getE11OrBuilder();
}
