// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: x13.proto

package demetra.x13.io.protobuf;

public final class X13Protos {
  private X13Protos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_x13_X11Spec_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_x13_X11Spec_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_x13_RegArimaSpec_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_x13_RegArimaSpec_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_x13_RegArimaSpec_BasicSpec_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_x13_RegArimaSpec_BasicSpec_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_x13_RegArimaSpec_TransformSpec_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_x13_RegArimaSpec_TransformSpec_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_x13_RegArimaSpec_OutlierSpec_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_x13_RegArimaSpec_OutlierSpec_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_x13_RegArimaSpec_OutlierSpec_Type_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_x13_RegArimaSpec_OutlierSpec_Type_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_x13_RegArimaSpec_AutoModelSpec_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_x13_RegArimaSpec_AutoModelSpec_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_x13_RegArimaSpec_EasterSpec_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_x13_RegArimaSpec_EasterSpec_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_x13_RegArimaSpec_TradingDaysSpec_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_x13_RegArimaSpec_TradingDaysSpec_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_x13_RegArimaSpec_RegressionSpec_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_x13_RegArimaSpec_RegressionSpec_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_x13_RegArimaSpec_EstimateSpec_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_x13_RegArimaSpec_EstimateSpec_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_x13_Spec_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_x13_Spec_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_x13_X11Results_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_x13_X11Results_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_x13_MStatistics_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_x13_MStatistics_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_x13_X13Preadjustment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_x13_X13Preadjustment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_x13_X13Finals_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_x13_X13Finals_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_x13_Diagnostics_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_x13_Diagnostics_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_x13_X13Results_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_x13_X13Results_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_x13_RegArimaOutput_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_x13_RegArimaOutput_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_x13_RegArimaOutput_DetailsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_x13_RegArimaOutput_DetailsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_x13_X13Output_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_x13_X13Output_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_x13_X13Output_DetailsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_x13_X13Output_DetailsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tx13.proto\022\003x13\032\rtoolkit.proto\032\017modelli" +
      "ng.proto\032\016regarima.proto\032\010sa.proto\"\250\002\n\007X" +
      "11Spec\022$\n\004mode\030\001 \001(\0162\026.x13.Decomposition" +
      "Mode\022\020\n\010seasonal\030\002 \001(\010\022\021\n\thenderson\030\003 \001(" +
      "\005\022%\n\010sfilters\030\004 \003(\0162\023.x13.SeasonalFilter" +
      "\022\014\n\004lsig\030\005 \001(\001\022\014\n\004usig\030\006 \001(\001\022\017\n\007nfcasts\030" +
      "\007 \001(\005\022\017\n\007nbcasts\030\010 \001(\005\022!\n\005sigma\030\t \001(\0162\022." +
      "x13.CalendarSigma\022\017\n\007vsigmas\030\n \003(\005\022\026\n\016ex" +
      "clude_fcasts\030\013 \001(\010\022!\n\004bias\030\014 \001(\0162\023.x13.B" +
      "iasCorrection\"\210\017\n\014RegArimaSpec\022*\n\005basic\030" +
      "\001 \001(\0132\033.x13.RegArimaSpec.BasicSpec\0222\n\ttr" +
      "ansform\030\002 \001(\0132\037.x13.RegArimaSpec.Transfo" +
      "rmSpec\022.\n\007outlier\030\003 \001(\0132\035.x13.RegArimaSp" +
      "ec.OutlierSpec\022#\n\005arima\030\004 \001(\0132\024.regarima" +
      ".SarimaSpec\0222\n\tautomodel\030\005 \001(\0132\037.x13.Reg" +
      "ArimaSpec.AutoModelSpec\0224\n\nregression\030\006 " +
      "\001(\0132 .x13.RegArimaSpec.RegressionSpec\0220\n" +
      "\010estimate\030\007 \001(\0132\036.x13.RegArimaSpec.Estim" +
      "ateSpec\032^\n\tBasicSpec\022\037\n\004span\030\001 \001(\0132\021.jd3" +
      ".TimeSelector\022\025\n\rpreprocessing\030\002 \001(\010\022\031\n\021" +
      "preliminary_check\030\003 \001(\010\032\233\001\n\rTransformSpe" +
      "c\0221\n\016transformation\030\001 \001(\0162\031.modelling.Tr" +
      "ansformation\022)\n\006adjust\030\002 \001(\0162\031.modelling" +
      ".LengthOfPeriod\022\017\n\007aicdiff\030\003 \001(\001\022\033\n\023outl" +
      "iers_correction\030\004 \001(\010\032\362\001\n\013OutlierSpec\0224\n" +
      "\010outliers\030\001 \003(\0132\".x13.RegArimaSpec.Outli" +
      "erSpec.Type\022\037\n\004span\030\002 \001(\0132\021.jd3.TimeSele" +
      "ctor\022\r\n\005defva\030\003 \001(\001\022\"\n\006method\030\004 \001(\0162\022.x1" +
      "3.OutlierMethod\022\027\n\017monthly_tc_rate\030\005 \001(\001" +
      "\022\017\n\007maxiter\030\006 \001(\005\022\r\n\005lsrun\030\007 \001(\005\032 \n\004Type" +
      "\022\014\n\004code\030\001 \001(\t\022\n\n\002va\030\002 \001(\001\032\314\001\n\rAutoModel" +
      "Spec\022\017\n\007enabled\030\001 \001(\010\022\020\n\010ljungbox\030\002 \001(\001\022" +
      "\014\n\004tsig\030\003 \001(\001\022\016\n\006predcv\030\004 \001(\001\022\017\n\007ubfinal" +
      "\030\005 \001(\001\022\013\n\003ub1\030\006 \001(\001\022\013\n\003ub2\030\007 \001(\001\022\016\n\006canc" +
      "el\030\010 \001(\001\022\013\n\003fct\030\t \001(\001\022\021\n\tacceptdef\030\n \001(\010" +
      "\022\r\n\005mixed\030\013 \001(\010\022\020\n\010balanced\030\014 \001(\010\032\205\001\n\nEa" +
      "sterSpec\022\035\n\004type\030\001 \001(\0162\017.x13.EasterType\022" +
      "\020\n\010duration\030\002 \001(\005\022!\n\004test\030\003 \001(\0162\023.x13.Re" +
      "gressionTest\022#\n\013coefficient\030\n \001(\0132\016.jd3." +
      "Parameter\032\330\002\n\017TradingDaysSpec\022\"\n\002td\030\001 \001(" +
      "\0162\026.modelling.TradingDays\022%\n\002lp\030\002 \001(\0162\031." +
      "modelling.LengthOfPeriod\022\020\n\010holidays\030\003 \001" +
      "(\t\022\r\n\005users\030\004 \003(\t\022\t\n\001w\030\005 \001(\005\022!\n\004test\030\006 \001" +
      "(\0162\023.x13.RegressionTest\022\'\n\004auto\030\007 \001(\0162\031." +
      "x13.AutomaticTradingDays\022\016\n\006ptest1\030\010 \001(\001" +
      "\022\016\n\006ptest2\030\t \001(\001\022\023\n\013auto_adjust\030\n \001(\010\022&\n" +
      "\016tdcoefficients\030\013 \003(\0132\016.jd3.Parameter\022%\n" +
      "\rlpcoefficient\030\014 \001(\0132\016.jd3.Parameter\032\303\002\n" +
      "\016RegressionSpec\022\034\n\004mean\030\001 \001(\0132\016.jd3.Para" +
      "meter\022\022\n\ncheck_mean\030\002 \001(\010\022-\n\002td\030\003 \001(\0132!." +
      "x13.RegArimaSpec.TradingDaysSpec\022,\n\006east" +
      "er\030\004 \001(\0132\034.x13.RegArimaSpec.EasterSpec\022$" +
      "\n\010outliers\030\005 \003(\0132\022.modelling.Outlier\022$\n\005" +
      "users\030\006 \003(\0132\025.modelling.TsVariable\0226\n\rin" +
      "terventions\030\007 \003(\0132\037.modelling.Interventi" +
      "onVariable\022\036\n\005ramps\030\010 \003(\0132\017.modelling.Ra" +
      "mp\032<\n\014EstimateSpec\022\037\n\004span\030\001 \001(\0132\021.jd3.T" +
      "imeSelector\022\013\n\003tol\030\002 \001(\001\"r\n\004Spec\022#\n\010rega" +
      "rima\030\001 \001(\0132\021.x13.RegArimaSpec\022\031\n\003x11\030\002 \001" +
      "(\0132\014.x13.X11Spec\022*\n\014benchmarking\030\003 \001(\0132\024" +
      ".sa.BenchmarkingSpec\"\334\010\n\nX11Results\022$\n\004m" +
      "ode\030\001 \001(\0162\026.x13.DecompositionMode\022\027\n\002d1\030" +
      "\002 \001(\0132\013.jd3.TsData\022\027\n\002d2\030\003 \001(\0132\013.jd3.TsD" +
      "ata\022\027\n\002d4\030\004 \001(\0132\013.jd3.TsData\022\027\n\002d5\030\005 \001(\013" +
      "2\013.jd3.TsData\022\027\n\002d6\030\006 \001(\0132\013.jd3.TsData\022\027" +
      "\n\002d7\030\007 \001(\0132\013.jd3.TsData\022\027\n\002d8\030\010 \001(\0132\013.jd" +
      "3.TsData\022\027\n\002d9\030\t \001(\0132\013.jd3.TsData\022\030\n\003d10" +
      "\030\n \001(\0132\013.jd3.TsData\022\030\n\003d11\030\013 \001(\0132\013.jd3.T" +
      "sData\022\030\n\003d12\030\014 \001(\0132\013.jd3.TsData\022\030\n\003d13\030\r" +
      " \001(\0132\013.jd3.TsData\0223\n\026final_seasonal_filt" +
      "ers\030\016 \003(\0162\023.x13.SeasonalFilter\022\036\n\026final_" +
      "henderson_filter\030\017 \001(\005\022\017\n\007icratio\030\020 \001(\001\022" +
      "\027\n\002b1\030\024 \001(\0132\013.jd3.TsData\022\027\n\002b2\030\025 \001(\0132\013.j" +
      "d3.TsData\022\027\n\002b3\030\026 \001(\0132\013.jd3.TsData\022\027\n\002b4" +
      "\030\027 \001(\0132\013.jd3.TsData\022\027\n\002b5\030\030 \001(\0132\013.jd3.Ts" +
      "Data\022\027\n\002b6\030\031 \001(\0132\013.jd3.TsData\022\027\n\002b7\030\032 \001(" +
      "\0132\013.jd3.TsData\022\027\n\002b8\030\033 \001(\0132\013.jd3.TsData\022" +
      "\027\n\002b9\030\034 \001(\0132\013.jd3.TsData\022\030\n\003b10\030\035 \001(\0132\013." +
      "jd3.TsData\022\030\n\003b11\030\036 \001(\0132\013.jd3.TsData\022\030\n\003" +
      "b13\030\037 \001(\0132\013.jd3.TsData\022\030\n\003b17\030  \001(\0132\013.jd" +
      "3.TsData\022\030\n\003b20\030! \001(\0132\013.jd3.TsData\022\027\n\002c1" +
      "\030( \001(\0132\013.jd3.TsData\022\027\n\002c2\030) \001(\0132\013.jd3.Ts" +
      "Data\022\027\n\002c4\030* \001(\0132\013.jd3.TsData\022\027\n\002c5\030+ \001(" +
      "\0132\013.jd3.TsData\022\027\n\002c6\030, \001(\0132\013.jd3.TsData\022" +
      "\027\n\002c7\030- \001(\0132\013.jd3.TsData\022\027\n\002c9\030. \001(\0132\013.j" +
      "d3.TsData\022\030\n\003c10\030/ \001(\0132\013.jd3.TsData\022\030\n\003c" +
      "11\0300 \001(\0132\013.jd3.TsData\022\030\n\003c13\0301 \001(\0132\013.jd3" +
      ".TsData\022\030\n\003c17\0302 \001(\0132\013.jd3.TsData\022\030\n\003c20" +
      "\0303 \001(\0132\013.jd3.TsData\"\253\001\n\013MStatistics\022\n\n\002m" +
      "1\030\001 \001(\001\022\n\n\002m2\030\002 \001(\001\022\n\n\002m3\030\003 \001(\001\022\n\n\002m4\030\004 " +
      "\001(\001\022\n\n\002m5\030\005 \001(\001\022\n\n\002m6\030\006 \001(\001\022\n\n\002m7\030\007 \001(\001\022" +
      "\n\n\002m8\030\010 \001(\001\022\n\n\002m9\030\t \001(\001\022\013\n\003m10\030\n \001(\001\022\013\n\003" +
      "m11\030\013 \001(\001\022\t\n\001q\030\014 \001(\001\022\013\n\003qm2\030\r \001(\001\"\303\001\n\020X1" +
      "3Preadjustment\022\027\n\002a1\030\001 \001(\0132\013.jd3.TsData\022" +
      "\030\n\003a1a\030\002 \001(\0132\013.jd3.TsData\022\030\n\003a1b\030\003 \001(\0132\013" +
      ".jd3.TsData\022\027\n\002a6\030\004 \001(\0132\013.jd3.TsData\022\027\n\002" +
      "a7\030\005 \001(\0132\013.jd3.TsData\022\027\n\002a8\030\006 \001(\0132\013.jd3." +
      "TsData\022\027\n\002a9\030\007 \001(\0132\013.jd3.TsData\"\355\002\n\tX13F" +
      "inals\022\035\n\010d11final\030\001 \001(\0132\013.jd3.TsData\022\035\n\010" +
      "d12final\030\002 \001(\0132\013.jd3.TsData\022\035\n\010d13final\030" +
      "\003 \001(\0132\013.jd3.TsData\022\030\n\003d16\030\004 \001(\0132\013.jd3.Ts" +
      "Data\022\030\n\003d18\030\005 \001(\0132\013.jd3.TsData\022\031\n\004d11a\030\006" +
      " \001(\0132\013.jd3.TsData\022\031\n\004d12a\030\007 \001(\0132\013.jd3.Ts" +
      "Data\022\031\n\004d16a\030\010 \001(\0132\013.jd3.TsData\022\031\n\004d18a\030" +
      "\t \001(\0132\013.jd3.TsData\022\027\n\002e1\030\n \001(\0132\013.jd3.TsD" +
      "ata\022\027\n\002e2\030\013 \001(\0132\013.jd3.TsData\022\027\n\002e3\030\014 \001(\013" +
      "2\013.jd3.TsData\022\030\n\003e11\030\r \001(\0132\013.jd3.TsData\"" +
      "4\n\013Diagnostics\022%\n\013mstatistics\030\001 \001(\0132\020.x1" +
      "3.MStatistics\"\205\002\n\nX13Results\022,\n\rpreadjus" +
      "tment\030\001 \001(\0132\025.x13.X13Preadjustment\022.\n\rpr" +
      "eprocessing\030\002 \001(\0132\027.regarima.RegArimaMod" +
      "el\022&\n\rdecomposition\030\003 \001(\0132\017.x13.X11Resul" +
      "ts\022\035\n\005final\030\004 \001(\0132\016.x13.X13Finals\022)\n\017dia" +
      "gnostics_x13\030\005 \001(\0132\020.x13.Diagnostics\022\'\n\016" +
      "diagnostics_sa\030\006 \001(\0132\017.sa.Diagnostics\"\251\002" +
      "\n\016RegArimaOutput\022\'\n\006result\030\001 \001(\0132\027.regar" +
      "ima.RegArimaModel\022*\n\017estimation_spec\030\002 \001" +
      "(\0132\021.x13.RegArimaSpec\022&\n\013result_spec\030\003 \001" +
      "(\0132\021.x13.RegArimaSpec\022 \n\003log\030\004 \001(\0132\023.jd3" +
      ".ProcessingLogs\0221\n\007details\030\005 \003(\0132 .x13.R" +
      "egArimaOutput.DetailsEntry\032E\n\014DetailsEnt" +
      "ry\022\013\n\003key\030\001 \001(\t\022$\n\005value\030\002 \001(\0132\025.jd3.Pro" +
      "cessingDetail:\0028\001\"\207\002\n\tX13Output\022\037\n\006resul" +
      "t\030\001 \001(\0132\017.x13.X13Results\022\"\n\017estimation_s" +
      "pec\030\002 \001(\0132\t.x13.Spec\022\036\n\013result_spec\030\003 \001(" +
      "\0132\t.x13.Spec\022 \n\003log\030\004 \001(\0132\023.jd3.Processi" +
      "ngLogs\022,\n\007details\030\005 \003(\0132\033.x13.X13Output." +
      "DetailsEntry\032E\n\014DetailsEntry\022\013\n\003key\030\001 \001(" +
      "\t\022$\n\005value\030\002 \001(\0132\025.jd3.ProcessingDetail:" +
      "\0028\001*\200\001\n\021DecompositionMode\022\020\n\014MODE_UNKNOW" +
      "N\020\000\022\021\n\rMODE_ADDITIVE\020\001\022\027\n\023MODE_MULTIPLIC" +
      "ATIVE\020\002\022\024\n\020MODE_LOGADDITIVE\020\003\022\027\n\023MODE_PS" +
      "EUDOADDITIVE\020\004*\350\001\n\016SeasonalFilter\022\027\n\023SEA" +
      "SONAL_FILTER_MSR\020\000\022\030\n\024SEASONAL_FILTER_S3" +
      "X1\020\001\022\030\n\024SEASONAL_FILTER_S3X3\020\002\022\030\n\024SEASON" +
      "AL_FILTER_S3X5\020\003\022\030\n\024SEASONAL_FILTER_S3X9" +
      "\020\004\022\031\n\025SEASONAL_FILTER_S3X15\020\005\022\032\n\026SEASONA" +
      "L_FILTER_STABLE\020\006\022\036\n\032SEASONAL_FILTER_X11" +
      "DEFAULT\020\007*R\n\rCalendarSigma\022\016\n\nSIGMA_NONE" +
      "\020\000\022\020\n\014SIGMA_SIGNIF\020\001\022\r\n\tSIGMA_ALL\020\002\022\020\n\014S" +
      "IGMA_SELECT\020\003*Q\n\016BiasCorrection\022\r\n\tBIAS_" +
      "NONE\020\000\022\017\n\013BIAS_LEGACY\020\001\022\017\n\013BIAS_SMOOTH\020\002" +
      "\022\016\n\nBIAS_RATIO\020\003*7\n\rOutlierMethod\022\022\n\016OUT" +
      "LIER_ADDONE\020\000\022\022\n\016OUTLIER_ADDALL\020\001*V\n\nEas" +
      "terType\022\021\n\rEASTER_UNUSED\020\000\022\023\n\017EASTER_STA" +
      "NDARD\020\001\022\021\n\rEASTER_JULIAN\020\002\022\r\n\tEASTER_SC\020" +
      "\003*<\n\016RegressionTest\022\013\n\007TEST_NO\020\000\022\014\n\010TEST" +
      "_ADD\020\001\022\017\n\013TEST_REMOVE\020\002*Z\n\024AutomaticTrad" +
      "ingDays\022\016\n\nTD_AUTO_NO\020\000\022\020\n\014TD_AUTO_WALD\020" +
      "\001\022\017\n\013TD_AUTO_AIC\020\002\022\017\n\013TD_AUTO_BIC\020\003B&\n\027d" +
      "emetra.x13.io.protobufB\tX13ProtosP\001P\000P\001P" +
      "\002P\003b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          demetra.toolkit.io.protobuf.ToolkitProtos.getDescriptor(),
          demetra.modelling.io.protobuf.ModellingProtos.getDescriptor(),
          demetra.regarima.io.protobuf.RegArimaProtos.getDescriptor(),
          demetra.sa.io.protobuf.SaProtos.getDescriptor(),
        });
    internal_static_x13_X11Spec_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_x13_X11Spec_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_x13_X11Spec_descriptor,
        new java.lang.String[] { "Mode", "Seasonal", "Henderson", "Sfilters", "Lsig", "Usig", "Nfcasts", "Nbcasts", "Sigma", "Vsigmas", "ExcludeFcasts", "Bias", });
    internal_static_x13_RegArimaSpec_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_x13_RegArimaSpec_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_x13_RegArimaSpec_descriptor,
        new java.lang.String[] { "Basic", "Transform", "Outlier", "Arima", "Automodel", "Regression", "Estimate", });
    internal_static_x13_RegArimaSpec_BasicSpec_descriptor =
      internal_static_x13_RegArimaSpec_descriptor.getNestedTypes().get(0);
    internal_static_x13_RegArimaSpec_BasicSpec_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_x13_RegArimaSpec_BasicSpec_descriptor,
        new java.lang.String[] { "Span", "Preprocessing", "PreliminaryCheck", });
    internal_static_x13_RegArimaSpec_TransformSpec_descriptor =
      internal_static_x13_RegArimaSpec_descriptor.getNestedTypes().get(1);
    internal_static_x13_RegArimaSpec_TransformSpec_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_x13_RegArimaSpec_TransformSpec_descriptor,
        new java.lang.String[] { "Transformation", "Adjust", "Aicdiff", "OutliersCorrection", });
    internal_static_x13_RegArimaSpec_OutlierSpec_descriptor =
      internal_static_x13_RegArimaSpec_descriptor.getNestedTypes().get(2);
    internal_static_x13_RegArimaSpec_OutlierSpec_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_x13_RegArimaSpec_OutlierSpec_descriptor,
        new java.lang.String[] { "Outliers", "Span", "Defva", "Method", "MonthlyTcRate", "Maxiter", "Lsrun", });
    internal_static_x13_RegArimaSpec_OutlierSpec_Type_descriptor =
      internal_static_x13_RegArimaSpec_OutlierSpec_descriptor.getNestedTypes().get(0);
    internal_static_x13_RegArimaSpec_OutlierSpec_Type_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_x13_RegArimaSpec_OutlierSpec_Type_descriptor,
        new java.lang.String[] { "Code", "Va", });
    internal_static_x13_RegArimaSpec_AutoModelSpec_descriptor =
      internal_static_x13_RegArimaSpec_descriptor.getNestedTypes().get(3);
    internal_static_x13_RegArimaSpec_AutoModelSpec_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_x13_RegArimaSpec_AutoModelSpec_descriptor,
        new java.lang.String[] { "Enabled", "Ljungbox", "Tsig", "Predcv", "Ubfinal", "Ub1", "Ub2", "Cancel", "Fct", "Acceptdef", "Mixed", "Balanced", });
    internal_static_x13_RegArimaSpec_EasterSpec_descriptor =
      internal_static_x13_RegArimaSpec_descriptor.getNestedTypes().get(4);
    internal_static_x13_RegArimaSpec_EasterSpec_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_x13_RegArimaSpec_EasterSpec_descriptor,
        new java.lang.String[] { "Type", "Duration", "Test", "Coefficient", });
    internal_static_x13_RegArimaSpec_TradingDaysSpec_descriptor =
      internal_static_x13_RegArimaSpec_descriptor.getNestedTypes().get(5);
    internal_static_x13_RegArimaSpec_TradingDaysSpec_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_x13_RegArimaSpec_TradingDaysSpec_descriptor,
        new java.lang.String[] { "Td", "Lp", "Holidays", "Users", "W", "Test", "Auto", "Ptest1", "Ptest2", "AutoAdjust", "Tdcoefficients", "Lpcoefficient", });
    internal_static_x13_RegArimaSpec_RegressionSpec_descriptor =
      internal_static_x13_RegArimaSpec_descriptor.getNestedTypes().get(6);
    internal_static_x13_RegArimaSpec_RegressionSpec_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_x13_RegArimaSpec_RegressionSpec_descriptor,
        new java.lang.String[] { "Mean", "CheckMean", "Td", "Easter", "Outliers", "Users", "Interventions", "Ramps", });
    internal_static_x13_RegArimaSpec_EstimateSpec_descriptor =
      internal_static_x13_RegArimaSpec_descriptor.getNestedTypes().get(7);
    internal_static_x13_RegArimaSpec_EstimateSpec_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_x13_RegArimaSpec_EstimateSpec_descriptor,
        new java.lang.String[] { "Span", "Tol", });
    internal_static_x13_Spec_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_x13_Spec_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_x13_Spec_descriptor,
        new java.lang.String[] { "Regarima", "X11", "Benchmarking", });
    internal_static_x13_X11Results_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_x13_X11Results_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_x13_X11Results_descriptor,
        new java.lang.String[] { "Mode", "D1", "D2", "D4", "D5", "D6", "D7", "D8", "D9", "D10", "D11", "D12", "D13", "FinalSeasonalFilters", "FinalHendersonFilter", "Icratio", "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "B10", "B11", "B13", "B17", "B20", "C1", "C2", "C4", "C5", "C6", "C7", "C9", "C10", "C11", "C13", "C17", "C20", });
    internal_static_x13_MStatistics_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_x13_MStatistics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_x13_MStatistics_descriptor,
        new java.lang.String[] { "M1", "M2", "M3", "M4", "M5", "M6", "M7", "M8", "M9", "M10", "M11", "Q", "Qm2", });
    internal_static_x13_X13Preadjustment_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_x13_X13Preadjustment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_x13_X13Preadjustment_descriptor,
        new java.lang.String[] { "A1", "A1A", "A1B", "A6", "A7", "A8", "A9", });
    internal_static_x13_X13Finals_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_x13_X13Finals_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_x13_X13Finals_descriptor,
        new java.lang.String[] { "D11Final", "D12Final", "D13Final", "D16", "D18", "D11A", "D12A", "D16A", "D18A", "E1", "E2", "E3", "E11", });
    internal_static_x13_Diagnostics_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_x13_Diagnostics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_x13_Diagnostics_descriptor,
        new java.lang.String[] { "Mstatistics", });
    internal_static_x13_X13Results_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_x13_X13Results_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_x13_X13Results_descriptor,
        new java.lang.String[] { "Preadjustment", "Preprocessing", "Decomposition", "Final", "DiagnosticsX13", "DiagnosticsSa", });
    internal_static_x13_RegArimaOutput_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_x13_RegArimaOutput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_x13_RegArimaOutput_descriptor,
        new java.lang.String[] { "Result", "EstimationSpec", "ResultSpec", "Log", "Details", });
    internal_static_x13_RegArimaOutput_DetailsEntry_descriptor =
      internal_static_x13_RegArimaOutput_descriptor.getNestedTypes().get(0);
    internal_static_x13_RegArimaOutput_DetailsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_x13_RegArimaOutput_DetailsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_x13_X13Output_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_x13_X13Output_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_x13_X13Output_descriptor,
        new java.lang.String[] { "Result", "EstimationSpec", "ResultSpec", "Log", "Details", });
    internal_static_x13_X13Output_DetailsEntry_descriptor =
      internal_static_x13_X13Output_descriptor.getNestedTypes().get(0);
    internal_static_x13_X13Output_DetailsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_x13_X13Output_DetailsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    demetra.toolkit.io.protobuf.ToolkitProtos.getDescriptor();
    demetra.modelling.io.protobuf.ModellingProtos.getDescriptor();
    demetra.regarima.io.protobuf.RegArimaProtos.getDescriptor();
    demetra.sa.io.protobuf.SaProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
