// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: x13.proto

package demetra.x13.io.protobuf;

/**
 * Protobuf type {@code x13.X13Preadjustment}
 */
public final class X13Preadjustment extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:x13.X13Preadjustment)
    X13PreadjustmentOrBuilder {
private static final long serialVersionUID = 0L;
  // Use X13Preadjustment.newBuilder() to construct.
  private X13Preadjustment(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private X13Preadjustment() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new X13Preadjustment();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private X13Preadjustment(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            demetra.toolkit.io.protobuf.ToolkitProtos.TsData.Builder subBuilder = null;
            if (a1_ != null) {
              subBuilder = a1_.toBuilder();
            }
            a1_ = input.readMessage(demetra.toolkit.io.protobuf.ToolkitProtos.TsData.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(a1_);
              a1_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            demetra.toolkit.io.protobuf.ToolkitProtos.TsData.Builder subBuilder = null;
            if (a1A_ != null) {
              subBuilder = a1A_.toBuilder();
            }
            a1A_ = input.readMessage(demetra.toolkit.io.protobuf.ToolkitProtos.TsData.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(a1A_);
              a1A_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            demetra.toolkit.io.protobuf.ToolkitProtos.TsData.Builder subBuilder = null;
            if (a1B_ != null) {
              subBuilder = a1B_.toBuilder();
            }
            a1B_ = input.readMessage(demetra.toolkit.io.protobuf.ToolkitProtos.TsData.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(a1B_);
              a1B_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            demetra.toolkit.io.protobuf.ToolkitProtos.TsData.Builder subBuilder = null;
            if (a6_ != null) {
              subBuilder = a6_.toBuilder();
            }
            a6_ = input.readMessage(demetra.toolkit.io.protobuf.ToolkitProtos.TsData.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(a6_);
              a6_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            demetra.toolkit.io.protobuf.ToolkitProtos.TsData.Builder subBuilder = null;
            if (a7_ != null) {
              subBuilder = a7_.toBuilder();
            }
            a7_ = input.readMessage(demetra.toolkit.io.protobuf.ToolkitProtos.TsData.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(a7_);
              a7_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            demetra.toolkit.io.protobuf.ToolkitProtos.TsData.Builder subBuilder = null;
            if (a8_ != null) {
              subBuilder = a8_.toBuilder();
            }
            a8_ = input.readMessage(demetra.toolkit.io.protobuf.ToolkitProtos.TsData.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(a8_);
              a8_ = subBuilder.buildPartial();
            }

            break;
          }
          case 58: {
            demetra.toolkit.io.protobuf.ToolkitProtos.TsData.Builder subBuilder = null;
            if (a9_ != null) {
              subBuilder = a9_.toBuilder();
            }
            a9_ = input.readMessage(demetra.toolkit.io.protobuf.ToolkitProtos.TsData.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(a9_);
              a9_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return demetra.x13.io.protobuf.X13Protos.internal_static_x13_X13Preadjustment_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return demetra.x13.io.protobuf.X13Protos.internal_static_x13_X13Preadjustment_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            demetra.x13.io.protobuf.X13Preadjustment.class, demetra.x13.io.protobuf.X13Preadjustment.Builder.class);
  }

  public static final int A1_FIELD_NUMBER = 1;
  private demetra.toolkit.io.protobuf.ToolkitProtos.TsData a1_;
  /**
   * <code>.jd3.TsData a1 = 1;</code>
   * @return Whether the a1 field is set.
   */
  @java.lang.Override
  public boolean hasA1() {
    return a1_ != null;
  }
  /**
   * <code>.jd3.TsData a1 = 1;</code>
   * @return The a1.
   */
  @java.lang.Override
  public demetra.toolkit.io.protobuf.ToolkitProtos.TsData getA1() {
    return a1_ == null ? demetra.toolkit.io.protobuf.ToolkitProtos.TsData.getDefaultInstance() : a1_;
  }
  /**
   * <code>.jd3.TsData a1 = 1;</code>
   */
  @java.lang.Override
  public demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder getA1OrBuilder() {
    return getA1();
  }

  public static final int A1A_FIELD_NUMBER = 2;
  private demetra.toolkit.io.protobuf.ToolkitProtos.TsData a1A_;
  /**
   * <code>.jd3.TsData a1a = 2;</code>
   * @return Whether the a1a field is set.
   */
  @java.lang.Override
  public boolean hasA1A() {
    return a1A_ != null;
  }
  /**
   * <code>.jd3.TsData a1a = 2;</code>
   * @return The a1a.
   */
  @java.lang.Override
  public demetra.toolkit.io.protobuf.ToolkitProtos.TsData getA1A() {
    return a1A_ == null ? demetra.toolkit.io.protobuf.ToolkitProtos.TsData.getDefaultInstance() : a1A_;
  }
  /**
   * <code>.jd3.TsData a1a = 2;</code>
   */
  @java.lang.Override
  public demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder getA1AOrBuilder() {
    return getA1A();
  }

  public static final int A1B_FIELD_NUMBER = 3;
  private demetra.toolkit.io.protobuf.ToolkitProtos.TsData a1B_;
  /**
   * <code>.jd3.TsData a1b = 3;</code>
   * @return Whether the a1b field is set.
   */
  @java.lang.Override
  public boolean hasA1B() {
    return a1B_ != null;
  }
  /**
   * <code>.jd3.TsData a1b = 3;</code>
   * @return The a1b.
   */
  @java.lang.Override
  public demetra.toolkit.io.protobuf.ToolkitProtos.TsData getA1B() {
    return a1B_ == null ? demetra.toolkit.io.protobuf.ToolkitProtos.TsData.getDefaultInstance() : a1B_;
  }
  /**
   * <code>.jd3.TsData a1b = 3;</code>
   */
  @java.lang.Override
  public demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder getA1BOrBuilder() {
    return getA1B();
  }

  public static final int A6_FIELD_NUMBER = 4;
  private demetra.toolkit.io.protobuf.ToolkitProtos.TsData a6_;
  /**
   * <code>.jd3.TsData a6 = 4;</code>
   * @return Whether the a6 field is set.
   */
  @java.lang.Override
  public boolean hasA6() {
    return a6_ != null;
  }
  /**
   * <code>.jd3.TsData a6 = 4;</code>
   * @return The a6.
   */
  @java.lang.Override
  public demetra.toolkit.io.protobuf.ToolkitProtos.TsData getA6() {
    return a6_ == null ? demetra.toolkit.io.protobuf.ToolkitProtos.TsData.getDefaultInstance() : a6_;
  }
  /**
   * <code>.jd3.TsData a6 = 4;</code>
   */
  @java.lang.Override
  public demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder getA6OrBuilder() {
    return getA6();
  }

  public static final int A7_FIELD_NUMBER = 5;
  private demetra.toolkit.io.protobuf.ToolkitProtos.TsData a7_;
  /**
   * <code>.jd3.TsData a7 = 5;</code>
   * @return Whether the a7 field is set.
   */
  @java.lang.Override
  public boolean hasA7() {
    return a7_ != null;
  }
  /**
   * <code>.jd3.TsData a7 = 5;</code>
   * @return The a7.
   */
  @java.lang.Override
  public demetra.toolkit.io.protobuf.ToolkitProtos.TsData getA7() {
    return a7_ == null ? demetra.toolkit.io.protobuf.ToolkitProtos.TsData.getDefaultInstance() : a7_;
  }
  /**
   * <code>.jd3.TsData a7 = 5;</code>
   */
  @java.lang.Override
  public demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder getA7OrBuilder() {
    return getA7();
  }

  public static final int A8_FIELD_NUMBER = 6;
  private demetra.toolkit.io.protobuf.ToolkitProtos.TsData a8_;
  /**
   * <code>.jd3.TsData a8 = 6;</code>
   * @return Whether the a8 field is set.
   */
  @java.lang.Override
  public boolean hasA8() {
    return a8_ != null;
  }
  /**
   * <code>.jd3.TsData a8 = 6;</code>
   * @return The a8.
   */
  @java.lang.Override
  public demetra.toolkit.io.protobuf.ToolkitProtos.TsData getA8() {
    return a8_ == null ? demetra.toolkit.io.protobuf.ToolkitProtos.TsData.getDefaultInstance() : a8_;
  }
  /**
   * <code>.jd3.TsData a8 = 6;</code>
   */
  @java.lang.Override
  public demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder getA8OrBuilder() {
    return getA8();
  }

  public static final int A9_FIELD_NUMBER = 7;
  private demetra.toolkit.io.protobuf.ToolkitProtos.TsData a9_;
  /**
   * <code>.jd3.TsData a9 = 7;</code>
   * @return Whether the a9 field is set.
   */
  @java.lang.Override
  public boolean hasA9() {
    return a9_ != null;
  }
  /**
   * <code>.jd3.TsData a9 = 7;</code>
   * @return The a9.
   */
  @java.lang.Override
  public demetra.toolkit.io.protobuf.ToolkitProtos.TsData getA9() {
    return a9_ == null ? demetra.toolkit.io.protobuf.ToolkitProtos.TsData.getDefaultInstance() : a9_;
  }
  /**
   * <code>.jd3.TsData a9 = 7;</code>
   */
  @java.lang.Override
  public demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder getA9OrBuilder() {
    return getA9();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (a1_ != null) {
      output.writeMessage(1, getA1());
    }
    if (a1A_ != null) {
      output.writeMessage(2, getA1A());
    }
    if (a1B_ != null) {
      output.writeMessage(3, getA1B());
    }
    if (a6_ != null) {
      output.writeMessage(4, getA6());
    }
    if (a7_ != null) {
      output.writeMessage(5, getA7());
    }
    if (a8_ != null) {
      output.writeMessage(6, getA8());
    }
    if (a9_ != null) {
      output.writeMessage(7, getA9());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (a1_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getA1());
    }
    if (a1A_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getA1A());
    }
    if (a1B_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getA1B());
    }
    if (a6_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getA6());
    }
    if (a7_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getA7());
    }
    if (a8_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getA8());
    }
    if (a9_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getA9());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof demetra.x13.io.protobuf.X13Preadjustment)) {
      return super.equals(obj);
    }
    demetra.x13.io.protobuf.X13Preadjustment other = (demetra.x13.io.protobuf.X13Preadjustment) obj;

    if (hasA1() != other.hasA1()) return false;
    if (hasA1()) {
      if (!getA1()
          .equals(other.getA1())) return false;
    }
    if (hasA1A() != other.hasA1A()) return false;
    if (hasA1A()) {
      if (!getA1A()
          .equals(other.getA1A())) return false;
    }
    if (hasA1B() != other.hasA1B()) return false;
    if (hasA1B()) {
      if (!getA1B()
          .equals(other.getA1B())) return false;
    }
    if (hasA6() != other.hasA6()) return false;
    if (hasA6()) {
      if (!getA6()
          .equals(other.getA6())) return false;
    }
    if (hasA7() != other.hasA7()) return false;
    if (hasA7()) {
      if (!getA7()
          .equals(other.getA7())) return false;
    }
    if (hasA8() != other.hasA8()) return false;
    if (hasA8()) {
      if (!getA8()
          .equals(other.getA8())) return false;
    }
    if (hasA9() != other.hasA9()) return false;
    if (hasA9()) {
      if (!getA9()
          .equals(other.getA9())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasA1()) {
      hash = (37 * hash) + A1_FIELD_NUMBER;
      hash = (53 * hash) + getA1().hashCode();
    }
    if (hasA1A()) {
      hash = (37 * hash) + A1A_FIELD_NUMBER;
      hash = (53 * hash) + getA1A().hashCode();
    }
    if (hasA1B()) {
      hash = (37 * hash) + A1B_FIELD_NUMBER;
      hash = (53 * hash) + getA1B().hashCode();
    }
    if (hasA6()) {
      hash = (37 * hash) + A6_FIELD_NUMBER;
      hash = (53 * hash) + getA6().hashCode();
    }
    if (hasA7()) {
      hash = (37 * hash) + A7_FIELD_NUMBER;
      hash = (53 * hash) + getA7().hashCode();
    }
    if (hasA8()) {
      hash = (37 * hash) + A8_FIELD_NUMBER;
      hash = (53 * hash) + getA8().hashCode();
    }
    if (hasA9()) {
      hash = (37 * hash) + A9_FIELD_NUMBER;
      hash = (53 * hash) + getA9().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static demetra.x13.io.protobuf.X13Preadjustment parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static demetra.x13.io.protobuf.X13Preadjustment parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static demetra.x13.io.protobuf.X13Preadjustment parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static demetra.x13.io.protobuf.X13Preadjustment parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static demetra.x13.io.protobuf.X13Preadjustment parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static demetra.x13.io.protobuf.X13Preadjustment parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static demetra.x13.io.protobuf.X13Preadjustment parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static demetra.x13.io.protobuf.X13Preadjustment parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static demetra.x13.io.protobuf.X13Preadjustment parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static demetra.x13.io.protobuf.X13Preadjustment parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static demetra.x13.io.protobuf.X13Preadjustment parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static demetra.x13.io.protobuf.X13Preadjustment parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(demetra.x13.io.protobuf.X13Preadjustment prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code x13.X13Preadjustment}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:x13.X13Preadjustment)
      demetra.x13.io.protobuf.X13PreadjustmentOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return demetra.x13.io.protobuf.X13Protos.internal_static_x13_X13Preadjustment_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return demetra.x13.io.protobuf.X13Protos.internal_static_x13_X13Preadjustment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              demetra.x13.io.protobuf.X13Preadjustment.class, demetra.x13.io.protobuf.X13Preadjustment.Builder.class);
    }

    // Construct using demetra.x13.io.protobuf.X13Preadjustment.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (a1Builder_ == null) {
        a1_ = null;
      } else {
        a1_ = null;
        a1Builder_ = null;
      }
      if (a1ABuilder_ == null) {
        a1A_ = null;
      } else {
        a1A_ = null;
        a1ABuilder_ = null;
      }
      if (a1BBuilder_ == null) {
        a1B_ = null;
      } else {
        a1B_ = null;
        a1BBuilder_ = null;
      }
      if (a6Builder_ == null) {
        a6_ = null;
      } else {
        a6_ = null;
        a6Builder_ = null;
      }
      if (a7Builder_ == null) {
        a7_ = null;
      } else {
        a7_ = null;
        a7Builder_ = null;
      }
      if (a8Builder_ == null) {
        a8_ = null;
      } else {
        a8_ = null;
        a8Builder_ = null;
      }
      if (a9Builder_ == null) {
        a9_ = null;
      } else {
        a9_ = null;
        a9Builder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return demetra.x13.io.protobuf.X13Protos.internal_static_x13_X13Preadjustment_descriptor;
    }

    @java.lang.Override
    public demetra.x13.io.protobuf.X13Preadjustment getDefaultInstanceForType() {
      return demetra.x13.io.protobuf.X13Preadjustment.getDefaultInstance();
    }

    @java.lang.Override
    public demetra.x13.io.protobuf.X13Preadjustment build() {
      demetra.x13.io.protobuf.X13Preadjustment result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public demetra.x13.io.protobuf.X13Preadjustment buildPartial() {
      demetra.x13.io.protobuf.X13Preadjustment result = new demetra.x13.io.protobuf.X13Preadjustment(this);
      if (a1Builder_ == null) {
        result.a1_ = a1_;
      } else {
        result.a1_ = a1Builder_.build();
      }
      if (a1ABuilder_ == null) {
        result.a1A_ = a1A_;
      } else {
        result.a1A_ = a1ABuilder_.build();
      }
      if (a1BBuilder_ == null) {
        result.a1B_ = a1B_;
      } else {
        result.a1B_ = a1BBuilder_.build();
      }
      if (a6Builder_ == null) {
        result.a6_ = a6_;
      } else {
        result.a6_ = a6Builder_.build();
      }
      if (a7Builder_ == null) {
        result.a7_ = a7_;
      } else {
        result.a7_ = a7Builder_.build();
      }
      if (a8Builder_ == null) {
        result.a8_ = a8_;
      } else {
        result.a8_ = a8Builder_.build();
      }
      if (a9Builder_ == null) {
        result.a9_ = a9_;
      } else {
        result.a9_ = a9Builder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof demetra.x13.io.protobuf.X13Preadjustment) {
        return mergeFrom((demetra.x13.io.protobuf.X13Preadjustment)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(demetra.x13.io.protobuf.X13Preadjustment other) {
      if (other == demetra.x13.io.protobuf.X13Preadjustment.getDefaultInstance()) return this;
      if (other.hasA1()) {
        mergeA1(other.getA1());
      }
      if (other.hasA1A()) {
        mergeA1A(other.getA1A());
      }
      if (other.hasA1B()) {
        mergeA1B(other.getA1B());
      }
      if (other.hasA6()) {
        mergeA6(other.getA6());
      }
      if (other.hasA7()) {
        mergeA7(other.getA7());
      }
      if (other.hasA8()) {
        mergeA8(other.getA8());
      }
      if (other.hasA9()) {
        mergeA9(other.getA9());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      demetra.x13.io.protobuf.X13Preadjustment parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (demetra.x13.io.protobuf.X13Preadjustment) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private demetra.toolkit.io.protobuf.ToolkitProtos.TsData a1_;
    private com.google.protobuf.SingleFieldBuilderV3<
        demetra.toolkit.io.protobuf.ToolkitProtos.TsData, demetra.toolkit.io.protobuf.ToolkitProtos.TsData.Builder, demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder> a1Builder_;
    /**
     * <code>.jd3.TsData a1 = 1;</code>
     * @return Whether the a1 field is set.
     */
    public boolean hasA1() {
      return a1Builder_ != null || a1_ != null;
    }
    /**
     * <code>.jd3.TsData a1 = 1;</code>
     * @return The a1.
     */
    public demetra.toolkit.io.protobuf.ToolkitProtos.TsData getA1() {
      if (a1Builder_ == null) {
        return a1_ == null ? demetra.toolkit.io.protobuf.ToolkitProtos.TsData.getDefaultInstance() : a1_;
      } else {
        return a1Builder_.getMessage();
      }
    }
    /**
     * <code>.jd3.TsData a1 = 1;</code>
     */
    public Builder setA1(demetra.toolkit.io.protobuf.ToolkitProtos.TsData value) {
      if (a1Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        a1_ = value;
        onChanged();
      } else {
        a1Builder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.jd3.TsData a1 = 1;</code>
     */
    public Builder setA1(
        demetra.toolkit.io.protobuf.ToolkitProtos.TsData.Builder builderForValue) {
      if (a1Builder_ == null) {
        a1_ = builderForValue.build();
        onChanged();
      } else {
        a1Builder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.jd3.TsData a1 = 1;</code>
     */
    public Builder mergeA1(demetra.toolkit.io.protobuf.ToolkitProtos.TsData value) {
      if (a1Builder_ == null) {
        if (a1_ != null) {
          a1_ =
            demetra.toolkit.io.protobuf.ToolkitProtos.TsData.newBuilder(a1_).mergeFrom(value).buildPartial();
        } else {
          a1_ = value;
        }
        onChanged();
      } else {
        a1Builder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.jd3.TsData a1 = 1;</code>
     */
    public Builder clearA1() {
      if (a1Builder_ == null) {
        a1_ = null;
        onChanged();
      } else {
        a1_ = null;
        a1Builder_ = null;
      }

      return this;
    }
    /**
     * <code>.jd3.TsData a1 = 1;</code>
     */
    public demetra.toolkit.io.protobuf.ToolkitProtos.TsData.Builder getA1Builder() {
      
      onChanged();
      return getA1FieldBuilder().getBuilder();
    }
    /**
     * <code>.jd3.TsData a1 = 1;</code>
     */
    public demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder getA1OrBuilder() {
      if (a1Builder_ != null) {
        return a1Builder_.getMessageOrBuilder();
      } else {
        return a1_ == null ?
            demetra.toolkit.io.protobuf.ToolkitProtos.TsData.getDefaultInstance() : a1_;
      }
    }
    /**
     * <code>.jd3.TsData a1 = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        demetra.toolkit.io.protobuf.ToolkitProtos.TsData, demetra.toolkit.io.protobuf.ToolkitProtos.TsData.Builder, demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder> 
        getA1FieldBuilder() {
      if (a1Builder_ == null) {
        a1Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
            demetra.toolkit.io.protobuf.ToolkitProtos.TsData, demetra.toolkit.io.protobuf.ToolkitProtos.TsData.Builder, demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder>(
                getA1(),
                getParentForChildren(),
                isClean());
        a1_ = null;
      }
      return a1Builder_;
    }

    private demetra.toolkit.io.protobuf.ToolkitProtos.TsData a1A_;
    private com.google.protobuf.SingleFieldBuilderV3<
        demetra.toolkit.io.protobuf.ToolkitProtos.TsData, demetra.toolkit.io.protobuf.ToolkitProtos.TsData.Builder, demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder> a1ABuilder_;
    /**
     * <code>.jd3.TsData a1a = 2;</code>
     * @return Whether the a1a field is set.
     */
    public boolean hasA1A() {
      return a1ABuilder_ != null || a1A_ != null;
    }
    /**
     * <code>.jd3.TsData a1a = 2;</code>
     * @return The a1a.
     */
    public demetra.toolkit.io.protobuf.ToolkitProtos.TsData getA1A() {
      if (a1ABuilder_ == null) {
        return a1A_ == null ? demetra.toolkit.io.protobuf.ToolkitProtos.TsData.getDefaultInstance() : a1A_;
      } else {
        return a1ABuilder_.getMessage();
      }
    }
    /**
     * <code>.jd3.TsData a1a = 2;</code>
     */
    public Builder setA1A(demetra.toolkit.io.protobuf.ToolkitProtos.TsData value) {
      if (a1ABuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        a1A_ = value;
        onChanged();
      } else {
        a1ABuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.jd3.TsData a1a = 2;</code>
     */
    public Builder setA1A(
        demetra.toolkit.io.protobuf.ToolkitProtos.TsData.Builder builderForValue) {
      if (a1ABuilder_ == null) {
        a1A_ = builderForValue.build();
        onChanged();
      } else {
        a1ABuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.jd3.TsData a1a = 2;</code>
     */
    public Builder mergeA1A(demetra.toolkit.io.protobuf.ToolkitProtos.TsData value) {
      if (a1ABuilder_ == null) {
        if (a1A_ != null) {
          a1A_ =
            demetra.toolkit.io.protobuf.ToolkitProtos.TsData.newBuilder(a1A_).mergeFrom(value).buildPartial();
        } else {
          a1A_ = value;
        }
        onChanged();
      } else {
        a1ABuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.jd3.TsData a1a = 2;</code>
     */
    public Builder clearA1A() {
      if (a1ABuilder_ == null) {
        a1A_ = null;
        onChanged();
      } else {
        a1A_ = null;
        a1ABuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.jd3.TsData a1a = 2;</code>
     */
    public demetra.toolkit.io.protobuf.ToolkitProtos.TsData.Builder getA1ABuilder() {
      
      onChanged();
      return getA1AFieldBuilder().getBuilder();
    }
    /**
     * <code>.jd3.TsData a1a = 2;</code>
     */
    public demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder getA1AOrBuilder() {
      if (a1ABuilder_ != null) {
        return a1ABuilder_.getMessageOrBuilder();
      } else {
        return a1A_ == null ?
            demetra.toolkit.io.protobuf.ToolkitProtos.TsData.getDefaultInstance() : a1A_;
      }
    }
    /**
     * <code>.jd3.TsData a1a = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        demetra.toolkit.io.protobuf.ToolkitProtos.TsData, demetra.toolkit.io.protobuf.ToolkitProtos.TsData.Builder, demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder> 
        getA1AFieldBuilder() {
      if (a1ABuilder_ == null) {
        a1ABuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            demetra.toolkit.io.protobuf.ToolkitProtos.TsData, demetra.toolkit.io.protobuf.ToolkitProtos.TsData.Builder, demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder>(
                getA1A(),
                getParentForChildren(),
                isClean());
        a1A_ = null;
      }
      return a1ABuilder_;
    }

    private demetra.toolkit.io.protobuf.ToolkitProtos.TsData a1B_;
    private com.google.protobuf.SingleFieldBuilderV3<
        demetra.toolkit.io.protobuf.ToolkitProtos.TsData, demetra.toolkit.io.protobuf.ToolkitProtos.TsData.Builder, demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder> a1BBuilder_;
    /**
     * <code>.jd3.TsData a1b = 3;</code>
     * @return Whether the a1b field is set.
     */
    public boolean hasA1B() {
      return a1BBuilder_ != null || a1B_ != null;
    }
    /**
     * <code>.jd3.TsData a1b = 3;</code>
     * @return The a1b.
     */
    public demetra.toolkit.io.protobuf.ToolkitProtos.TsData getA1B() {
      if (a1BBuilder_ == null) {
        return a1B_ == null ? demetra.toolkit.io.protobuf.ToolkitProtos.TsData.getDefaultInstance() : a1B_;
      } else {
        return a1BBuilder_.getMessage();
      }
    }
    /**
     * <code>.jd3.TsData a1b = 3;</code>
     */
    public Builder setA1B(demetra.toolkit.io.protobuf.ToolkitProtos.TsData value) {
      if (a1BBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        a1B_ = value;
        onChanged();
      } else {
        a1BBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.jd3.TsData a1b = 3;</code>
     */
    public Builder setA1B(
        demetra.toolkit.io.protobuf.ToolkitProtos.TsData.Builder builderForValue) {
      if (a1BBuilder_ == null) {
        a1B_ = builderForValue.build();
        onChanged();
      } else {
        a1BBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.jd3.TsData a1b = 3;</code>
     */
    public Builder mergeA1B(demetra.toolkit.io.protobuf.ToolkitProtos.TsData value) {
      if (a1BBuilder_ == null) {
        if (a1B_ != null) {
          a1B_ =
            demetra.toolkit.io.protobuf.ToolkitProtos.TsData.newBuilder(a1B_).mergeFrom(value).buildPartial();
        } else {
          a1B_ = value;
        }
        onChanged();
      } else {
        a1BBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.jd3.TsData a1b = 3;</code>
     */
    public Builder clearA1B() {
      if (a1BBuilder_ == null) {
        a1B_ = null;
        onChanged();
      } else {
        a1B_ = null;
        a1BBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.jd3.TsData a1b = 3;</code>
     */
    public demetra.toolkit.io.protobuf.ToolkitProtos.TsData.Builder getA1BBuilder() {
      
      onChanged();
      return getA1BFieldBuilder().getBuilder();
    }
    /**
     * <code>.jd3.TsData a1b = 3;</code>
     */
    public demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder getA1BOrBuilder() {
      if (a1BBuilder_ != null) {
        return a1BBuilder_.getMessageOrBuilder();
      } else {
        return a1B_ == null ?
            demetra.toolkit.io.protobuf.ToolkitProtos.TsData.getDefaultInstance() : a1B_;
      }
    }
    /**
     * <code>.jd3.TsData a1b = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        demetra.toolkit.io.protobuf.ToolkitProtos.TsData, demetra.toolkit.io.protobuf.ToolkitProtos.TsData.Builder, demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder> 
        getA1BFieldBuilder() {
      if (a1BBuilder_ == null) {
        a1BBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            demetra.toolkit.io.protobuf.ToolkitProtos.TsData, demetra.toolkit.io.protobuf.ToolkitProtos.TsData.Builder, demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder>(
                getA1B(),
                getParentForChildren(),
                isClean());
        a1B_ = null;
      }
      return a1BBuilder_;
    }

    private demetra.toolkit.io.protobuf.ToolkitProtos.TsData a6_;
    private com.google.protobuf.SingleFieldBuilderV3<
        demetra.toolkit.io.protobuf.ToolkitProtos.TsData, demetra.toolkit.io.protobuf.ToolkitProtos.TsData.Builder, demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder> a6Builder_;
    /**
     * <code>.jd3.TsData a6 = 4;</code>
     * @return Whether the a6 field is set.
     */
    public boolean hasA6() {
      return a6Builder_ != null || a6_ != null;
    }
    /**
     * <code>.jd3.TsData a6 = 4;</code>
     * @return The a6.
     */
    public demetra.toolkit.io.protobuf.ToolkitProtos.TsData getA6() {
      if (a6Builder_ == null) {
        return a6_ == null ? demetra.toolkit.io.protobuf.ToolkitProtos.TsData.getDefaultInstance() : a6_;
      } else {
        return a6Builder_.getMessage();
      }
    }
    /**
     * <code>.jd3.TsData a6 = 4;</code>
     */
    public Builder setA6(demetra.toolkit.io.protobuf.ToolkitProtos.TsData value) {
      if (a6Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        a6_ = value;
        onChanged();
      } else {
        a6Builder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.jd3.TsData a6 = 4;</code>
     */
    public Builder setA6(
        demetra.toolkit.io.protobuf.ToolkitProtos.TsData.Builder builderForValue) {
      if (a6Builder_ == null) {
        a6_ = builderForValue.build();
        onChanged();
      } else {
        a6Builder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.jd3.TsData a6 = 4;</code>
     */
    public Builder mergeA6(demetra.toolkit.io.protobuf.ToolkitProtos.TsData value) {
      if (a6Builder_ == null) {
        if (a6_ != null) {
          a6_ =
            demetra.toolkit.io.protobuf.ToolkitProtos.TsData.newBuilder(a6_).mergeFrom(value).buildPartial();
        } else {
          a6_ = value;
        }
        onChanged();
      } else {
        a6Builder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.jd3.TsData a6 = 4;</code>
     */
    public Builder clearA6() {
      if (a6Builder_ == null) {
        a6_ = null;
        onChanged();
      } else {
        a6_ = null;
        a6Builder_ = null;
      }

      return this;
    }
    /**
     * <code>.jd3.TsData a6 = 4;</code>
     */
    public demetra.toolkit.io.protobuf.ToolkitProtos.TsData.Builder getA6Builder() {
      
      onChanged();
      return getA6FieldBuilder().getBuilder();
    }
    /**
     * <code>.jd3.TsData a6 = 4;</code>
     */
    public demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder getA6OrBuilder() {
      if (a6Builder_ != null) {
        return a6Builder_.getMessageOrBuilder();
      } else {
        return a6_ == null ?
            demetra.toolkit.io.protobuf.ToolkitProtos.TsData.getDefaultInstance() : a6_;
      }
    }
    /**
     * <code>.jd3.TsData a6 = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        demetra.toolkit.io.protobuf.ToolkitProtos.TsData, demetra.toolkit.io.protobuf.ToolkitProtos.TsData.Builder, demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder> 
        getA6FieldBuilder() {
      if (a6Builder_ == null) {
        a6Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
            demetra.toolkit.io.protobuf.ToolkitProtos.TsData, demetra.toolkit.io.protobuf.ToolkitProtos.TsData.Builder, demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder>(
                getA6(),
                getParentForChildren(),
                isClean());
        a6_ = null;
      }
      return a6Builder_;
    }

    private demetra.toolkit.io.protobuf.ToolkitProtos.TsData a7_;
    private com.google.protobuf.SingleFieldBuilderV3<
        demetra.toolkit.io.protobuf.ToolkitProtos.TsData, demetra.toolkit.io.protobuf.ToolkitProtos.TsData.Builder, demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder> a7Builder_;
    /**
     * <code>.jd3.TsData a7 = 5;</code>
     * @return Whether the a7 field is set.
     */
    public boolean hasA7() {
      return a7Builder_ != null || a7_ != null;
    }
    /**
     * <code>.jd3.TsData a7 = 5;</code>
     * @return The a7.
     */
    public demetra.toolkit.io.protobuf.ToolkitProtos.TsData getA7() {
      if (a7Builder_ == null) {
        return a7_ == null ? demetra.toolkit.io.protobuf.ToolkitProtos.TsData.getDefaultInstance() : a7_;
      } else {
        return a7Builder_.getMessage();
      }
    }
    /**
     * <code>.jd3.TsData a7 = 5;</code>
     */
    public Builder setA7(demetra.toolkit.io.protobuf.ToolkitProtos.TsData value) {
      if (a7Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        a7_ = value;
        onChanged();
      } else {
        a7Builder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.jd3.TsData a7 = 5;</code>
     */
    public Builder setA7(
        demetra.toolkit.io.protobuf.ToolkitProtos.TsData.Builder builderForValue) {
      if (a7Builder_ == null) {
        a7_ = builderForValue.build();
        onChanged();
      } else {
        a7Builder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.jd3.TsData a7 = 5;</code>
     */
    public Builder mergeA7(demetra.toolkit.io.protobuf.ToolkitProtos.TsData value) {
      if (a7Builder_ == null) {
        if (a7_ != null) {
          a7_ =
            demetra.toolkit.io.protobuf.ToolkitProtos.TsData.newBuilder(a7_).mergeFrom(value).buildPartial();
        } else {
          a7_ = value;
        }
        onChanged();
      } else {
        a7Builder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.jd3.TsData a7 = 5;</code>
     */
    public Builder clearA7() {
      if (a7Builder_ == null) {
        a7_ = null;
        onChanged();
      } else {
        a7_ = null;
        a7Builder_ = null;
      }

      return this;
    }
    /**
     * <code>.jd3.TsData a7 = 5;</code>
     */
    public demetra.toolkit.io.protobuf.ToolkitProtos.TsData.Builder getA7Builder() {
      
      onChanged();
      return getA7FieldBuilder().getBuilder();
    }
    /**
     * <code>.jd3.TsData a7 = 5;</code>
     */
    public demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder getA7OrBuilder() {
      if (a7Builder_ != null) {
        return a7Builder_.getMessageOrBuilder();
      } else {
        return a7_ == null ?
            demetra.toolkit.io.protobuf.ToolkitProtos.TsData.getDefaultInstance() : a7_;
      }
    }
    /**
     * <code>.jd3.TsData a7 = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        demetra.toolkit.io.protobuf.ToolkitProtos.TsData, demetra.toolkit.io.protobuf.ToolkitProtos.TsData.Builder, demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder> 
        getA7FieldBuilder() {
      if (a7Builder_ == null) {
        a7Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
            demetra.toolkit.io.protobuf.ToolkitProtos.TsData, demetra.toolkit.io.protobuf.ToolkitProtos.TsData.Builder, demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder>(
                getA7(),
                getParentForChildren(),
                isClean());
        a7_ = null;
      }
      return a7Builder_;
    }

    private demetra.toolkit.io.protobuf.ToolkitProtos.TsData a8_;
    private com.google.protobuf.SingleFieldBuilderV3<
        demetra.toolkit.io.protobuf.ToolkitProtos.TsData, demetra.toolkit.io.protobuf.ToolkitProtos.TsData.Builder, demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder> a8Builder_;
    /**
     * <code>.jd3.TsData a8 = 6;</code>
     * @return Whether the a8 field is set.
     */
    public boolean hasA8() {
      return a8Builder_ != null || a8_ != null;
    }
    /**
     * <code>.jd3.TsData a8 = 6;</code>
     * @return The a8.
     */
    public demetra.toolkit.io.protobuf.ToolkitProtos.TsData getA8() {
      if (a8Builder_ == null) {
        return a8_ == null ? demetra.toolkit.io.protobuf.ToolkitProtos.TsData.getDefaultInstance() : a8_;
      } else {
        return a8Builder_.getMessage();
      }
    }
    /**
     * <code>.jd3.TsData a8 = 6;</code>
     */
    public Builder setA8(demetra.toolkit.io.protobuf.ToolkitProtos.TsData value) {
      if (a8Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        a8_ = value;
        onChanged();
      } else {
        a8Builder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.jd3.TsData a8 = 6;</code>
     */
    public Builder setA8(
        demetra.toolkit.io.protobuf.ToolkitProtos.TsData.Builder builderForValue) {
      if (a8Builder_ == null) {
        a8_ = builderForValue.build();
        onChanged();
      } else {
        a8Builder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.jd3.TsData a8 = 6;</code>
     */
    public Builder mergeA8(demetra.toolkit.io.protobuf.ToolkitProtos.TsData value) {
      if (a8Builder_ == null) {
        if (a8_ != null) {
          a8_ =
            demetra.toolkit.io.protobuf.ToolkitProtos.TsData.newBuilder(a8_).mergeFrom(value).buildPartial();
        } else {
          a8_ = value;
        }
        onChanged();
      } else {
        a8Builder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.jd3.TsData a8 = 6;</code>
     */
    public Builder clearA8() {
      if (a8Builder_ == null) {
        a8_ = null;
        onChanged();
      } else {
        a8_ = null;
        a8Builder_ = null;
      }

      return this;
    }
    /**
     * <code>.jd3.TsData a8 = 6;</code>
     */
    public demetra.toolkit.io.protobuf.ToolkitProtos.TsData.Builder getA8Builder() {
      
      onChanged();
      return getA8FieldBuilder().getBuilder();
    }
    /**
     * <code>.jd3.TsData a8 = 6;</code>
     */
    public demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder getA8OrBuilder() {
      if (a8Builder_ != null) {
        return a8Builder_.getMessageOrBuilder();
      } else {
        return a8_ == null ?
            demetra.toolkit.io.protobuf.ToolkitProtos.TsData.getDefaultInstance() : a8_;
      }
    }
    /**
     * <code>.jd3.TsData a8 = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        demetra.toolkit.io.protobuf.ToolkitProtos.TsData, demetra.toolkit.io.protobuf.ToolkitProtos.TsData.Builder, demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder> 
        getA8FieldBuilder() {
      if (a8Builder_ == null) {
        a8Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
            demetra.toolkit.io.protobuf.ToolkitProtos.TsData, demetra.toolkit.io.protobuf.ToolkitProtos.TsData.Builder, demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder>(
                getA8(),
                getParentForChildren(),
                isClean());
        a8_ = null;
      }
      return a8Builder_;
    }

    private demetra.toolkit.io.protobuf.ToolkitProtos.TsData a9_;
    private com.google.protobuf.SingleFieldBuilderV3<
        demetra.toolkit.io.protobuf.ToolkitProtos.TsData, demetra.toolkit.io.protobuf.ToolkitProtos.TsData.Builder, demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder> a9Builder_;
    /**
     * <code>.jd3.TsData a9 = 7;</code>
     * @return Whether the a9 field is set.
     */
    public boolean hasA9() {
      return a9Builder_ != null || a9_ != null;
    }
    /**
     * <code>.jd3.TsData a9 = 7;</code>
     * @return The a9.
     */
    public demetra.toolkit.io.protobuf.ToolkitProtos.TsData getA9() {
      if (a9Builder_ == null) {
        return a9_ == null ? demetra.toolkit.io.protobuf.ToolkitProtos.TsData.getDefaultInstance() : a9_;
      } else {
        return a9Builder_.getMessage();
      }
    }
    /**
     * <code>.jd3.TsData a9 = 7;</code>
     */
    public Builder setA9(demetra.toolkit.io.protobuf.ToolkitProtos.TsData value) {
      if (a9Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        a9_ = value;
        onChanged();
      } else {
        a9Builder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.jd3.TsData a9 = 7;</code>
     */
    public Builder setA9(
        demetra.toolkit.io.protobuf.ToolkitProtos.TsData.Builder builderForValue) {
      if (a9Builder_ == null) {
        a9_ = builderForValue.build();
        onChanged();
      } else {
        a9Builder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.jd3.TsData a9 = 7;</code>
     */
    public Builder mergeA9(demetra.toolkit.io.protobuf.ToolkitProtos.TsData value) {
      if (a9Builder_ == null) {
        if (a9_ != null) {
          a9_ =
            demetra.toolkit.io.protobuf.ToolkitProtos.TsData.newBuilder(a9_).mergeFrom(value).buildPartial();
        } else {
          a9_ = value;
        }
        onChanged();
      } else {
        a9Builder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.jd3.TsData a9 = 7;</code>
     */
    public Builder clearA9() {
      if (a9Builder_ == null) {
        a9_ = null;
        onChanged();
      } else {
        a9_ = null;
        a9Builder_ = null;
      }

      return this;
    }
    /**
     * <code>.jd3.TsData a9 = 7;</code>
     */
    public demetra.toolkit.io.protobuf.ToolkitProtos.TsData.Builder getA9Builder() {
      
      onChanged();
      return getA9FieldBuilder().getBuilder();
    }
    /**
     * <code>.jd3.TsData a9 = 7;</code>
     */
    public demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder getA9OrBuilder() {
      if (a9Builder_ != null) {
        return a9Builder_.getMessageOrBuilder();
      } else {
        return a9_ == null ?
            demetra.toolkit.io.protobuf.ToolkitProtos.TsData.getDefaultInstance() : a9_;
      }
    }
    /**
     * <code>.jd3.TsData a9 = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        demetra.toolkit.io.protobuf.ToolkitProtos.TsData, demetra.toolkit.io.protobuf.ToolkitProtos.TsData.Builder, demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder> 
        getA9FieldBuilder() {
      if (a9Builder_ == null) {
        a9Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
            demetra.toolkit.io.protobuf.ToolkitProtos.TsData, demetra.toolkit.io.protobuf.ToolkitProtos.TsData.Builder, demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder>(
                getA9(),
                getParentForChildren(),
                isClean());
        a9_ = null;
      }
      return a9Builder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:x13.X13Preadjustment)
  }

  // @@protoc_insertion_point(class_scope:x13.X13Preadjustment)
  private static final demetra.x13.io.protobuf.X13Preadjustment DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new demetra.x13.io.protobuf.X13Preadjustment();
  }

  public static demetra.x13.io.protobuf.X13Preadjustment getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<X13Preadjustment>
      PARSER = new com.google.protobuf.AbstractParser<X13Preadjustment>() {
    @java.lang.Override
    public X13Preadjustment parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new X13Preadjustment(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<X13Preadjustment> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<X13Preadjustment> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public demetra.x13.io.protobuf.X13Preadjustment getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

