// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: x13.proto

package demetra.x13.io.protobuf;

public interface X13PreadjustmentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:x13.X13Preadjustment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.jd3.TsData a1 = 1;</code>
   * @return Whether the a1 field is set.
   */
  boolean hasA1();
  /**
   * <code>.jd3.TsData a1 = 1;</code>
   * @return The a1.
   */
  demetra.toolkit.io.protobuf.ToolkitProtos.TsData getA1();
  /**
   * <code>.jd3.TsData a1 = 1;</code>
   */
  demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder getA1OrBuilder();

  /**
   * <code>.jd3.TsData a1a = 2;</code>
   * @return Whether the a1a field is set.
   */
  boolean hasA1A();
  /**
   * <code>.jd3.TsData a1a = 2;</code>
   * @return The a1a.
   */
  demetra.toolkit.io.protobuf.ToolkitProtos.TsData getA1A();
  /**
   * <code>.jd3.TsData a1a = 2;</code>
   */
  demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder getA1AOrBuilder();

  /**
   * <code>.jd3.TsData a1b = 3;</code>
   * @return Whether the a1b field is set.
   */
  boolean hasA1B();
  /**
   * <code>.jd3.TsData a1b = 3;</code>
   * @return The a1b.
   */
  demetra.toolkit.io.protobuf.ToolkitProtos.TsData getA1B();
  /**
   * <code>.jd3.TsData a1b = 3;</code>
   */
  demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder getA1BOrBuilder();

  /**
   * <code>.jd3.TsData a6 = 4;</code>
   * @return Whether the a6 field is set.
   */
  boolean hasA6();
  /**
   * <code>.jd3.TsData a6 = 4;</code>
   * @return The a6.
   */
  demetra.toolkit.io.protobuf.ToolkitProtos.TsData getA6();
  /**
   * <code>.jd3.TsData a6 = 4;</code>
   */
  demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder getA6OrBuilder();

  /**
   * <code>.jd3.TsData a7 = 5;</code>
   * @return Whether the a7 field is set.
   */
  boolean hasA7();
  /**
   * <code>.jd3.TsData a7 = 5;</code>
   * @return The a7.
   */
  demetra.toolkit.io.protobuf.ToolkitProtos.TsData getA7();
  /**
   * <code>.jd3.TsData a7 = 5;</code>
   */
  demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder getA7OrBuilder();

  /**
   * <code>.jd3.TsData a8 = 6;</code>
   * @return Whether the a8 field is set.
   */
  boolean hasA8();
  /**
   * <code>.jd3.TsData a8 = 6;</code>
   * @return The a8.
   */
  demetra.toolkit.io.protobuf.ToolkitProtos.TsData getA8();
  /**
   * <code>.jd3.TsData a8 = 6;</code>
   */
  demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder getA8OrBuilder();

  /**
   * <code>.jd3.TsData a9 = 7;</code>
   * @return Whether the a9 field is set.
   */
  boolean hasA9();
  /**
   * <code>.jd3.TsData a9 = 7;</code>
   * @return The a9.
   */
  demetra.toolkit.io.protobuf.ToolkitProtos.TsData getA9();
  /**
   * <code>.jd3.TsData a9 = 7;</code>
   */
  demetra.toolkit.io.protobuf.ToolkitProtos.TsDataOrBuilder getA9OrBuilder();
}
